#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#include "bb_core.h"
#include "bb_emit.h"

#ifdef __cplusplus
extern "C" {
#endif

// Shared "wifi" cache/telemetry topic constant. Referenced by bb_wifi_http
// (host+espidf) — the bb_cache tag, HTTP route tag, and openapi schema name
// cannot drift independently. Not the same topic as "net.health"
// (bb_net_health) — that name is out of scope for this constant.
#define BB_TOPIC_WIFI "wifi"

// ---------------------------------------------------------------------------
// Public types — usable on every backend.
// ---------------------------------------------------------------------------

#define WIFI_SCAN_MAX 20

typedef struct {
    char ssid[33];
    int8_t rssi;
    bool secure;   // true if not WIFI_AUTH_OPEN
} bb_wifi_ap_t;

// Portable WiFi disconnect-reason contract (KB 820, PR1). Every backend
// (ESP-IDF, CC3000, WiFiS3/R4, host) maps its own backend-specific
// disconnect/status code onto this single enum -- no raw backend-specific
// numeric code is ever surfaced from bb_wifi's public API or wire format
// again. Wire consumers (GET /api/wifi, GET /api/diag/net) see only the
// stable STRING label from bb_wifi_disc_reason_str(); this enum (and its
// ordinal values) is an internal implementation detail, free to change
// across releases without a wire break.
typedef enum {
    BB_WIFI_DISC_UNKNOWN = 0,
    BB_WIFI_DISC_AUTH_FAIL,
    BB_WIFI_DISC_ASSOC_FAIL,
    BB_WIFI_DISC_HANDSHAKE_TIMEOUT,
    BB_WIFI_DISC_CONNECTION_LOST,
    BB_WIFI_DISC_NO_AP_FOUND,
    BB_WIFI_DISC_INACTIVITY,
    BB_WIFI_DISC_DEAUTH,
    BB_WIFI_DISC_BEACON_TIMEOUT,
    BB_WIFI_DISC_BB_LOST_IP,        // breadboard-injected: IP lost while associated
    BB_WIFI_DISC_BB_EGRESS_DEAD,    // breadboard-injected: gateway probe declared dead
    BB_WIFI_DISC_BB_NO_IP_WATCHDOG, // breadboard-injected: associated-but-no-IP watchdog
    BB_WIFI_DISC_COUNT,             // sentinel -- not a valid reason value
} bb_wifi_disc_reason_t;

// Snapshot of the current STA connection. Populated by bb_wifi_get_info.
// On backends that don't surface a given field, it is zeroed.
typedef struct {
    char ssid[33];       // SSID of associated AP, empty if not connected
    uint8_t bssid[6];    // BSSID of associated AP
    int8_t rssi;         // signal strength, 0 if not connected
    char ip[16];         // dotted-quad IPv4, "0.0.0.0" if no IP
    bool connected;      // true iff has_ip
    bb_wifi_disc_reason_t disc_reason; // last disconnect reason (portable enum)
    uint32_t disc_age_s; // seconds since last disconnect, 0 if never
    int retry_count;     // STA retry attempts since last connect
} bb_wifi_info_t;

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------

// Idempotent one-shot bring-up of the underlying network stack. On ESP-IDF
// this initializes esp_netif and the default event loop. On backends where
// the platform handles this implicitly (Arduino), this is a BB_OK no-op so
// portable consumer code can call it unconditionally.
bb_err_t bb_wifi_ensure_net_stack(void);

// Inject the OTA-image-validated query bb_wifi's cold-boot timeout / persistent-
// disconnect safeguard / retry-forever gates read to decide whether the running
// image is "trusted" (skip cold-boot reboot, retry indefinitely, don't bump
// boot_count toward AP-fallback). Composition-only — bb_wifi does not self-
// register a default and has no dependency on bb_ota_validator. Pass NULL to
// clear the callback. When no callback is set, bb_wifi treats the running
// image as trusted (returns true) — a build without bb_ota_validator has no
// rollback watchdog at all, so the running image is implicitly permanent and
// every one of these gates should behave exactly as it did when the direct
// bb_ota_is_validated() call always found a validated image. MUST be called
// before bb_wifi's EARLY-tier init runs (bb_app_init_early() under codegen,
// or the equivalent hand-wired call), whichever composition path is in use,
// so it is set before the EARLY-tier bb_wifi_autoinit runs.
// Setter + public invoke generated by the bb_core "single-slot injected
// callback" macro (bb_callback_slot.h, BB_CALLBACK_SLOT_RET), instantiated
// in platform/host/bb_wifi/bb_wifi_emit.c (host+esp compiled) as
// bb_wifi_internal_ota_validated(); NULL cb -> invoke returns true (see the
// "implicitly permanent" rationale above). invoke reads its own file-static
// slot (no separate dispatch(cb, ...) symbol) -- exercised via the real
// shipped setter/invoke pair by test/test_host/test_bb_wifi.c; the macro's
// generic fire/no-fire logic is covered once, in isolation, by bb_core's
// test/test_host/test_bb_callback_slot.c.
typedef bool (*bb_wifi_ota_validated_fn)(void);
void bb_wifi_set_ota_validated_cb(bb_wifi_ota_validated_fn cb);

// STA mode connect. Returns an error on connect timeout (intended for
// provisioning retry loops); blocks until connected or timeout.
bb_err_t bb_wifi_init_sta(void);

// Registry hook — connects STA using stored creds (or skips if unconfigured),
// applying the pending-creds-try / retry-forever-when-validated policies.
// requires=storage_nvs: bb_settings' wifi ssid/pass/hostname descriptors are
// hardcoded to backend="nvs" (see bb_settings.h), so any app composing
// bb_wifi_autoinit via codegen must also compose bb_storage_nvs (provides=
// storage_nvs, bb_storage_nvs.h) -- this edge forces bb_storage_nvs_register()
// to run first in the same EARLY tier, rather than leaving it to accidental
// parse order. A composer that omits bb_storage_nvs hits a hard
// MissingProviderError at codegen time instead of a silent BB_ERR_NOT_FOUND
// on stored creds at boot.
// bbtool:init tier=early fn=bb_wifi_autoinit requires=storage_nvs
bb_err_t bb_wifi_autoinit(void);

// Stop and restart the WiFi STA driver to clear wedged driver state.
// Re-applies the saved STA config and inactive-time. Calls esp_wifi_connect()
// explicitly; safe to call from the reconn task context.
// Only available on ESP-IDF platform.
void bb_wifi_restart_sta(void);

// App-driven WiFi recovery request.
// Returns BB_OK immediately (non-blocking). If the STA already has no IP,
// this is a no-op (BB_OK) — the FSM already owns recovery.
// Debounced: at most one action per CONFIG_BB_WIFI_RECOVERY_COOLDOWN_S.
// When triggered, signals the reconn task to call bb_wifi_restart_sta().
// Bumps bb_wifi_get_egress_dead_count() and logs reason (never silent).
// Always compiled; safe to call from any task context.
bb_err_t bb_wifi_request_recovery(const char *reason);

// ---------------------------------------------------------------------------
// Hostname
// ---------------------------------------------------------------------------

// Set the DHCP host name (Option 12) advertised by the STA netif.
// Independent of mDNS — call bb_mdns_set_hostname() separately if you
// want the same value on both surfaces. Safe to call before STA connects;
// the value is sent on the next DHCP DISCOVER/REQUEST. Returns
// BB_ERR_INVALID_ARG on NULL/empty hostname; BB_ERR_INVALID_STATE if
// the STA netif isn't initialized yet. On backends without hostname
// support (e.g. CC3000), returns BB_OK no-op.
bb_err_t bb_wifi_set_hostname(const char *hostname);

// ---------------------------------------------------------------------------
// Scan
// ---------------------------------------------------------------------------
// On backends without scan support, the blocking variant returns 0 and the
// async pair is a BB_OK / 0 no-op — callers can invoke them unconditionally.

// Blocking WiFi scan. Returns number of APs found (up to max_results).
int bb_wifi_scan_networks(bb_wifi_ap_t *results, int max_results);

// Start a non-blocking WiFi scan in the background. Returns immediately.
void bb_wifi_scan_start_async(void);

// Get cached WiFi scan results. Returns number of APs (0 if no scan done).
int bb_wifi_scan_get_cached(bb_wifi_ap_t *results, int max_results);

// ---------------------------------------------------------------------------
// Net-event edges (KB 781) — the three STA lifecycle edges published via the
// generic emit seam below (bb_wifi_set_emit / BB_WIFI_EVENT_TOPIC).
// ---------------------------------------------------------------------------

typedef enum {
    BB_WIFI_NET_EVT_GOT_IP = 0,
    BB_WIFI_NET_EVT_DISCONNECT,
    BB_WIFI_NET_EVT_LOST_IP,
    BB_WIFI_NET_EVT_REBOOT_DENIED, // B1-805: reconnect FSM escalation denied
                                    // (budget/boot-fail-count) -- fell back to
                                    // backoff instead of rebooting.
} bb_wifi_net_event_t;

// The reason is passed explicitly as a call argument -- NOT read back via
// bb_wifi_get_disconnect() from inside the emit callback. Reading it back
// races wifi_reconn_on_disconnect() (which updates the async disconnect-reason
// state AFTER bb_wifi_publish_net_event() fires for BB_WIFI_NET_EVT_DISCONNECT
// in the WIFI_EVENT_STA_DISCONNECTED handler), so a callback calling
// bb_wifi_get_disconnect() would observe a stale value. Passing the reason
// through the call closes that race.
//
// Per-edge value:
//   BB_WIFI_NET_EVT_GOT_IP        -> BB_WIFI_DISC_UNKNOWN (not meaningful)
//   BB_WIFI_NET_EVT_DISCONNECT    -> the mapped reason for this disconnect
//                                    (bb_wifi_map_esp_reason() of the esp_wifi
//                                    WIFI_REASON_* code)
//   BB_WIFI_NET_EVT_LOST_IP       -> BB_WIFI_DISC_BB_LOST_IP
//   BB_WIFI_NET_EVT_REBOOT_DENIED -> the last disconnect reason (mapped),
//                                    or BB_WIFI_DISC_UNKNOWN when the denial
//                                    was on a connect-timeout stall (no
//                                    disconnect reason code applies)
//
// `evt` is the discriminator, not `reason` alone: BB_WIFI_DISC_UNKNOWN is
// overloaded -- on GOT_IP it's a "not applicable" filler (there is no
// disconnect), on DISCONNECT it's a genuine disconnect whose ESP reason
// code isn't in bb_wifi_map_esp_reason()'s table. A consumer that buckets
// purely on `reason` (e.g. metrics/logging) without also keying on `evt`
// will conflate those two populations.

// ---------------------------------------------------------------------------
// wifi.net event contract (KB 820, PR1) + generic emit seam (PR3)
// ---------------------------------------------------------------------------
// bb_wifi stays bb_event-FREE (no bb_event include, no bb_event CMakeLists
// dependency) -- but it publishes this payload itself, via a single-slot
// seam: bb_wifi_set_emit(bb_emit_fn) (bb_emit.h, bb_core). That slot is
// bus-shaped ((topic, id, payload, size), no bb_event types) so composition
// can wire it directly to bb_event_emit without bb_wifi ever including
// bb_event -- the caller supplies the emit sink.
// bb_wifi_emit_baseline() additionally lets a late-registering consumer
// request a one-shot synthesis of the CURRENT state onto the emit slot (see
// its declaration below) -- the wifi.net contract's NO RETAIN/REPLAY note
// (below) is otherwise unaffected: a late bb_event subscriber still must
// call bb_wifi_has_ip()/bb_wifi_get_info() itself before subscribing, since
// baseline-post only helps a consumer that registers before subscribing,
// not one that subscribes to bb_event directly.
//
// Topic: "wifi.net" -- distinct from BB_TOPIC_WIFI ("wifi") above, which is
// reserved for the bb_cache/HTTP snapshot (GET /api/wifi). Do not reuse
// BB_TOPIC_WIFI for the event stream.
#define BB_WIFI_EVENT_TOPIC "wifi.net"

// Payload published on BB_WIFI_EVENT_TOPIC. The bb_wifi_net_event_t edge
// (GOT_IP/DISCONNECT/LOST_IP) is carried as the bb_event id (0/1/2) --
// id-as-discriminator, the same precedent as bb_health_stack.c -- not a
// field in this struct.
//   ip         dotted-quad IPv4, populated ONLY on GOT_IP; zeroed otherwise.
//   disc_reason  meaningful on DISCONNECT/LOST_IP; BB_WIFI_DISC_UNKNOWN on
//                GOT_IP (see the evt/reason disambiguation note on
//                bb_wifi_net_event_t above -- key on the bb_event id
//                (edge), not disc_reason alone).
//
// NO RETAIN/REPLAY: bb_event core has no retain (replay is SSE-only). A
// consumer needing current state at subscribe time calls bb_wifi_has_ip() /
// bb_wifi_get_info() synchronously once, then subscribes.
typedef struct {
    char ip[16];
    bb_wifi_disc_reason_t disc_reason;
} bb_wifi_event_payload_t;

// Pure builder for bb_wifi_event_payload_t (KB 820, PR2 -- host-testable,
// bb_event-free). NULL-safe: no-op if out==NULL. Zeroes *out first, then
// sets disc_reason to a straight passthrough of `reason`. out->ip is
// populated ONLY when evt==BB_WIFI_NET_EVT_GOT_IP and ip!=NULL -- every
// other evt, or a NULL ip, leaves out->ip blank (this is the ip-blanking
// enforcement point for the wire contract above). Lives in bb_wifi (not the
// composition-level bridge) so it stays host-testable without pulling in
// bb_event; the intended caller is that bridge.
void bb_wifi_event_payload_build(bb_wifi_event_payload_t *out,
                                 bb_wifi_net_event_t evt,
                                 bb_wifi_disc_reason_t reason,
                                 const char *ip);

// Register a generic emit sink (bb_emit_fn, bb_core/bb_emit.h) for the
// wifi.net payload -- bus-shaped (topic, id, payload, size). NULL clears it.
// Fired on BB_WIFI_EVENT_TOPIC at the three STA lifecycle edges
// (got_ip/disconnect/lost_ip), with the id/payload built via
// bb_wifi_event_payload_build.
// Single-slot, single-consumer, null-safe: register once at init, before
// bb_wifi_init()/bb_wifi_init_sta(), from a single thread.
// bbtool:init tier=early fn=bb_wifi_set_emit consumes=emit_sink order=0
void bb_wifi_set_emit(bb_emit_fn cb);

// One-shot synthesis of the CURRENT STA state (bb_wifi_has_ip()/
// bb_wifi_get_info()) onto the generic emit slot, as a wifi.net GOT_IP or
// DISCONNECT payload. No-op if the slot is unset. Intended for a
// generic-seam consumer that registers via bb_wifi_set_emit() after boot
// and wants the current state without waiting for the next real edge -- it
// does NOT change the wifi.net contract's NO RETAIN/REPLAY guarantee for a
// bb_event subscriber (see above): that consumer still calls
// bb_wifi_has_ip()/bb_wifi_get_info() itself before subscribing.
void bb_wifi_emit_baseline(void);

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------

void bb_wifi_get_disconnect(bb_wifi_disc_reason_t *reason, int64_t *age_us);
int  bb_wifi_get_retry_count(void);
bb_err_t bb_wifi_get_ip_str(char *out, size_t out_len);
bb_err_t bb_wifi_get_rssi(int8_t *out);
bool bb_wifi_has_ip(void);

// True iff the STA is L2-associated to an AP (regardless of IP state).
// Boot-safe: safe to call before the wifi driver is fully up (returns
// false, not an error). Host stub is test-injectable via
// bb_wifi_test_set_associated() (BB_WIFI_TESTING).
bool bb_wifi_is_associated(void);

// Populate out with a snapshot of the current STA state. Fields the
// backend cannot supply are zeroed. Returns BB_ERR_INVALID_ARG on null.
bb_err_t bb_wifi_get_info(bb_wifi_info_t *out);

// Lost-IP-while-associated recovery counters.
// Return 0 if the reconnect manager is not active or no lost-IP has occurred.
uint32_t bb_wifi_get_lost_ip_count(void);
uint32_t bb_wifi_get_lost_ip_age_s(void);

// Egress-dead recovery counter: times the active gateway-probe found the
// gateway unreachable and triggered bb_wifi_restart_sta. Returns 0 if the
// reconnect manager is not active or no egress-dead event has occurred.
uint32_t bb_wifi_get_egress_dead_count(void);

// Times bb_wifi_restart_sta() has been called as part of any WiFi recovery path.
// Incremented inside bb_wifi_restart_sta() only — callers must NOT increment it.
// Returns 0 if bb_wifi_restart_sta() has never been invoked.
uint32_t bb_wifi_get_restart_sta_count(void);

// Roam / BSSID-change counter (B1-497) — OBSERVE-ONLY telemetry, wired to NO
// recovery action. Incremented in the STA_CONNECTED event handler when the
// newly-associated BSSID differs from the previously cached one (a roam
// within the same SSID, or reassociation to a different AP). The first
// connect since boot (no prior cached BSSID) does NOT count as a roam.
// Returns 0 if no roam has occurred since boot.
uint32_t bb_wifi_get_roam_count(void);

// Seconds since the most recent roam event (see bb_wifi_get_roam_count).
// Returns 0 if no roam has occurred since boot (sentinel — matches
// bb_wifi_get_lost_ip_age_s()).
uint32_t bb_wifi_get_roam_age_s(void);

// Pure roam-detection predicate (B1-497): true iff prior_bssid is non-zero
// (i.e. this is not the first connect since boot) and differs from
// new_bssid. Host-testable; the sole production caller is the ESP-IDF
// STA_CONNECTED handler in bb_wifi.c. Safe to call with NULL pointers
// (returns false).
bool bb_wifi_is_roam(const uint8_t prior_bssid[6], const uint8_t new_bssid[6]);

// RSSI at the moment of the most recent WIFI_EVENT_STA_DISCONNECTED event.
// Captured from the periodically-refreshed RSSI cache (s_cached_rssi) before
// the AP record is torn down, avoiding a stale/invalid read inside the handler.
// Returns INT8_MIN if no disconnect has occurred since boot (sentinel = "no reading").
int8_t bb_wifi_get_disconnect_rssi(void);

// Duration in seconds of the STA's most recently ENDED connected session
// (elapsed time between the WIFI_EVENT_STA_CONNECTED that started it and
// the following WIFI_EVENT_STA_DISCONNECTED that ended it). OBSERVE-ONLY
// telemetry — captured at disconnect time, no recovery action attached.
// Returns 0 if no session has ended since boot (sentinel — matches
// bb_wifi_get_lost_ip_age_s()/bb_wifi_get_roam_age_s()). The value is frozen
// at the last disconnect; it does not update live while connected.
uint32_t bb_wifi_get_last_session_s(void);

// Human-readable, wire-stable label for a bb_wifi_disc_reason_t value: one
// static string literal per enum member (e.g. "handshake_timeout",
// "bb_lost_ip"). This label -- never a raw numeric code -- is what crosses
// the wire (GET /api/wifi "disc_reason", GET /api/diag/net
// "last_disconnect_reason"/"reason_histogram" keys/"top_reason"). Never
// returns NULL; an out-of-range value defensively falls back to "unknown".
// Pure, host-testable, fully reentrant (every branch returns a static
// string literal) — no platform dependency.
const char *bb_wifi_disc_reason_str(bb_wifi_disc_reason_t reason);

// Deprecated aliases — retained for source compatibility with any external
// callers that referenced the old numeric sentinel values (99/100/101, no
// longer wire-visible now that the wire carries string labels). New code
// should reference the bb_wifi_disc_reason_t enum members directly.
#define BB_WIFI_REASON_BB_LOST_IP        BB_WIFI_DISC_BB_LOST_IP
#define BB_WIFI_REASON_BB_EGRESS_DEAD    BB_WIFI_DISC_BB_EGRESS_DEAD
#define BB_WIFI_REASON_BB_NO_IP_WATCHDOG BB_WIFI_DISC_BB_NO_IP_WATCHDOG

// Map an esp_wifi WIFI_EVENT_STA_DISCONNECTED reason code onto the portable
// bb_wifi_disc_reason_t bucket. Pure; deliberately does NOT include
// esp_wifi_types.h (this file compiles on host too) -- the numeric literals
// are the standard esp_wifi WIFI_REASON_* values, named in each comment
// (mirrors bb_wifi_disc_reason_str's existing convention). Unmapped codes
// return BB_WIFI_DISC_UNKNOWN. ESP-IDF backend only production caller
// (platform/espidf/bb_wifi/wifi_reconn.c); host-testable.
bb_wifi_disc_reason_t bb_wifi_map_esp_reason(uint16_t esp_code);

// Map an Arduino WiFiS3 wl_status_t value onto the portable
// bb_wifi_disc_reason_t bucket. Takes a plain int (not wl_status_t) so this
// header stays free of the Arduino WiFiS3.h include; the numeric literals
// are the standard wl_status_t values, named in each comment. Unmapped
// codes return BB_WIFI_DISC_UNKNOWN. R4 backend only production caller
// (platform/arduino/bb_wifi/bb_wifi_r4.cpp); host-testable.
bb_wifi_disc_reason_t bb_wifi_map_wl_status(int wl_status);

// Copy the disconnect reason histogram into out[0..len-1], one bucket per
// bb_wifi_disc_reason_t value (out[BB_WIFI_DISC_HANDSHAKE_TIMEOUT] etc.);
// out[BB_WIFI_DISC_BB_LOST_IP/_BB_EGRESS_DEAD/_BB_NO_IP_WATCHDOG] are the
// breadboard-injected buckets. If the reconnect manager is not active, out
// is zeroed. Safe to call with NULL or len==0 (no-op).
void bb_wifi_get_reason_histogram(uint16_t *out, size_t len);

// Find the top standard (non-breadboard-injected) disconnect reason in a
// BB_WIFI_DISC_COUNT-entry histogram as returned by
// bb_wifi_get_reason_histogram. Skips the three breadboard-injected buckets
// (BB_WIFI_DISC_BB_LOST_IP / _BB_EGRESS_DEAD / _BB_NO_IP_WATCHDOG). Sets
// *out_count to the highest non-injected count found (0 if all zero, or
// hist is NULL); returns the bb_wifi_disc_reason_t bucket for that count, or
// BB_WIFI_DISC_UNKNOWN if all are zero. hist must point to at least
// BB_WIFI_DISC_COUNT entries. Pure, no side effects; safe to call with
// hist==NULL or out_count==NULL.
bb_wifi_disc_reason_t bb_wifi_reason_histogram_top(const uint16_t *hist, uint16_t *out_count);

// ---------------------------------------------------------------------------
// Link-quality classifier (RSSI bucket + hysteresis) — moved from
// bb_net_health (net_health teardown PR-B). Pure, host-testable, no
// ESP-IDF dependency. bb_net_health's early_warning fusion calls this to get
// the current link bucket before combining it with MQTT-fused signal.
// ---------------------------------------------------------------------------

// RSSI-bucket thresholds (compile-time overridable). On ESP-IDF, Kconfig
// generates CONFIG_BB_WIFI_* symbols; bridge them here so menuconfig changes
// take effect. On the host build there is no sdkconfig, so we fall straight
// through to the numeric fallbacks.
#ifdef ESP_PLATFORM
#  ifdef CONFIG_BB_WIFI_RSSI_GOOD
#    define BB_WIFI_RSSI_GOOD CONFIG_BB_WIFI_RSSI_GOOD
#  endif
#endif
#ifndef BB_WIFI_RSSI_GOOD
#define BB_WIFI_RSSI_GOOD     (-67)  // rssi >= -67 -> GOOD
#endif

#ifdef ESP_PLATFORM
#  ifdef CONFIG_BB_WIFI_RSSI_MARGINAL_LO
#    define BB_WIFI_RSSI_MARGINAL_LO CONFIG_BB_WIFI_RSSI_MARGINAL_LO
#  endif
#endif
#ifndef BB_WIFI_RSSI_MARGINAL_LO
#define BB_WIFI_RSSI_MARGINAL_LO  (-75)  // -75 <= rssi <= -68 -> MARGINAL
#endif

// Hysteresis sample counts
#ifdef ESP_PLATFORM
#  ifdef CONFIG_BB_WIFI_HYST_DOWN
#    define BB_WIFI_HYST_DOWN CONFIG_BB_WIFI_HYST_DOWN
#  endif
#endif
#ifndef BB_WIFI_HYST_DOWN
#define BB_WIFI_HYST_DOWN  3  // consecutive worse-bucket samples before downgrade
#endif

#ifdef ESP_PLATFORM
#  ifdef CONFIG_BB_WIFI_HYST_UP
#    define BB_WIFI_HYST_UP CONFIG_BB_WIFI_HYST_UP
#  endif
#endif
#ifndef BB_WIFI_HYST_UP
#define BB_WIFI_HYST_UP    3  // consecutive better-bucket samples before upgrade
#endif

// Ordered link-quality bucket. GOOD > MARGINAL > POOR in signal quality.
typedef enum {
    BB_WIFI_LINK_GOOD     = 0,
    BB_WIFI_LINK_MARGINAL = 1,
    BB_WIFI_LINK_POOR     = 2,
} bb_wifi_link_state_t;

// Caller-owned hysteresis state, passed to every bb_wifi_classify_link call.
// Zero-init is valid (initialized=false seeds directly from the raw bucket
// on the first call, bypassing hysteresis so the boot snapshot reflects
// reality immediately).
typedef struct {
    bb_wifi_link_state_t current_state; // current published bucket
    int                  down_count;    // consecutive worse-bucket samples
    int                  up_count;      // consecutive better-bucket samples
    bool                 initialized;   // false until first classify call
} bb_wifi_link_hyst_t;

// Classify raw RSSI into a bb_wifi_link_state_t bucket, applying hysteresis
// against the caller-owned *st. Thread-safety: the caller owns st; no
// internal locking. Pure, host-testable — no side effects beyond *st.
bb_wifi_link_state_t bb_wifi_classify_link(bb_wifi_link_hyst_t *st, int8_t rssi);

// Return a static string for a bb_wifi_link_state_t value.
// "good", "marginal", or "poor". Never returns NULL.
const char *bb_wifi_link_state_str(bb_wifi_link_state_t state);

// ---------------------------------------------------------------------------
// WiFi discrimination mode — pure classifier over (associated, has_ip),
// moved from bb_net_health (net_health teardown PR-B).
// ---------------------------------------------------------------------------

/**
 * Coarse WiFi connectivity discriminator, distinguishing "no IP while
 * associated" (zombie/DHCP failure) from "not associated at all" (out of
 * range, wrong creds, AP down). OBSERVE-ONLY — no recovery action is wired
 * to this classification; it exists purely for /api/diag/net and net.health
 * observability.
 */
typedef enum {
    BB_WIFI_MODE_OK             = 0, // associated && has_ip
    BB_WIFI_MODE_NO_IP          = 1, // associated && !has_ip
    BB_WIFI_MODE_NOT_ASSOCIATED = 2, // !associated
} bb_wifi_mode_t;

/**
 * Pure classifier: derives a bb_wifi_mode_t from the current association and
 * IP-acquisition state. No side-effects; host-testable.
 */
bb_wifi_mode_t bb_wifi_classify_mode(bool associated, bool has_ip);

/**
 * Return a static string for a bb_wifi_mode_t value.
 * "ok", "no_ip", or "not_associated". Never returns NULL.
 */
const char *bb_wifi_mode_str(bb_wifi_mode_t mode);

#ifdef ESP_PLATFORM
// ICMP ping a target IPv4 address. target_addr is a raw IPv4 address in
// esp_ip4_addr byte order (i.e. the same value as esp_ip4_addr_t.addr).
// Sends a single echo-request and waits up to timeout_ms for an echo-reply.
// Sets *out_reachable to true on reply, false on timeout. Always compiled
// (reusable; CI validates the esp_ping symbol). Returns BB_OK or an error.
bb_err_t bb_wifi_ping(uint32_t target_addr, uint32_t timeout_ms,
                      bool *out_reachable);

// Convenience wrapper: pings the current STA default gateway. Returns false
// if no IP/gateway info is available or if the ICMP ping times out.
bool bb_wifi_gateway_reachable(uint32_t timeout_ms);
#endif /* ESP_PLATFORM */

// ---------------------------------------------------------------------------
// Gateway-reachability probe (observe-only, B1-518 PR2)
// ---------------------------------------------------------------------------
// Runs on a dedicated worker task (see platform/espidf/bb_wifi/bb_wifi_gw_probe.c),
// gated by CONFIG_BB_WIFI_GW_PROBE_ENABLE. OBSERVE-ONLY: the worker's policy
// decision is always discarded — this signal never triggers recovery on its
// own (#578). bb_net_health (a later PR) pulls this status for correlation.

// Snapshot of the gateway-probe worker's last observed state. Populated by
// bb_wifi_get_gateway_status.
typedef struct {
    bool     gw_reachable;      // result of the most recent gateway ping
    uint8_t  gw_fail_streak;    // consecutive probe failures (observe-owned state,
                                 // SEPARATE from the live reconnect FSM's streak)
    uint32_t gw_probe_count;    // cumulative probes run since boot
    uint32_t gw_fail_count;     // cumulative probe failures since boot
    uint32_t gw_dead_count;     // cumulative times the observe-only classifier
                                 // would have tripped WIFI_RECONN_ACTION_RECONNECT_NOW
                                 // (action is DISCARDED, never acted on)
    uint64_t last_gw_probe_ms;  // bb_clock_now_ms64() at the last probe, 0 = never run
} bb_wifi_gw_status_t;

// Populate out with the gateway-probe worker's last observed state.
// Returns BB_ERR_INVALID_ARG on NULL out. On ESP-IDF, returns
// BB_ERR_INVALID_STATE if the probe worker has never started (e.g.
// CONFIG_BB_WIFI_GW_PROBE_ENABLE=n). Host stub always returns BB_OK with a
// zeroed status (gw_reachable=false) unless overridden via
// bb_wifi_host_set_gateway_status (BB_WIFI_TESTING).
bb_err_t bb_wifi_get_gateway_status(bb_wifi_gw_status_t *out);

#if defined(CONFIG_BB_WIFI_GW_PROBE_ENABLE) && CONFIG_BB_WIFI_GW_PROBE_ENABLE
// Registry hook — starts the dedicated gateway-probe worker task.
// bbtool:init tier=pre_http fn=bb_wifi_gw_probe_start
bb_err_t bb_wifi_gw_probe_start(void);
#else
// No-op stub when the gateway-probe worker is compiled out (default) --
// codegen's `// bbtool:init` marker scan has no preprocessor awareness
// (grep-time, see wire_parse.py), so bb_app_init.c unconditionally calls
// this fn; mirrors the bb_cache.h Kconfig-bridge stub pattern.
static inline bb_err_t bb_wifi_gw_probe_start(void) { return BB_OK; }
#endif /* defined(CONFIG_BB_WIFI_GW_PROBE_ENABLE) && CONFIG_BB_WIFI_GW_PROBE_ENABLE */

// bb_wifi_emit_section / bb_wifi_emit_status (bb_json_t-based JSON emitters)
// moved to bb_wifi_http.h (PR1, KB 781) — bb_wifi's public header no longer
// includes bb_json.h so the STA core stays free of the http/json/openapi
// dependency closure. Callers that need the JSON emitters (e.g. bb_health)
// include bb_wifi_http.h instead.

// ---------------------------------------------------------------------------
// Runtime WiFi reconfigure (brick-safe pending-creds try)
// ---------------------------------------------------------------------------

// Stage new WiFi credentials and reboot to try them. On boot, if the pending
// credentials succeed (got-IP), they are committed as the new live creds.
// On timeout they are cleared and the device reboots onto the prior live creds
// without incrementing boot_count. Returns BB_OK after staging and arming the
// deferred reboot; the response to the caller can flush before the restart
// fires. Returns BB_ERR_UNSUPPORTED when CONFIG_BB_WIFI_RECONFIGURE is off.
bb_err_t bb_wifi_reconfigure(const char *ssid, const char *pass);

// ---------------------------------------------------------------------------
// Transport (consumed by Arduino bb_http)
// ---------------------------------------------------------------------------
// Generic non-blocking accept-loop transport. The Arduino bb_http backend
// consumes it so it can stay radio-agnostic across WiFiS3 and CC3000
// shields. ESP-IDF bb_http uses esp_http_server directly and the ESP-IDF
// backend stubs these out as BB_ERR_INVALID_STATE.

typedef struct bb_conn bb_conn_t;

// Begin listening on port. Idempotent. The backend may defer the actual
// listen syscall until the first bb_wifi_accept call (CC3000 in particular
// requires server construction from loop() context, not init).
bb_err_t bb_wifi_listen(uint16_t port);

// Non-blocking accept. Returns BB_OK with *out set to a connection handle,
// or *out == NULL if no connection is pending. The handle is owned by the
// backend; release it with bb_conn_close.
bb_err_t bb_wifi_accept(bb_conn_t **out);

// Number of bytes available to read without blocking.
int  bb_conn_available(bb_conn_t *c);

// Read up to n bytes. Returns bytes read, 0 if none available, -1 on error.
int  bb_conn_read(bb_conn_t *c, uint8_t *buf, size_t n);

// Write up to n bytes. Returns bytes written, -1 on error.
int  bb_conn_write(bb_conn_t *c, const uint8_t *buf, size_t n);

// Close the connection and release the handle.
void bb_conn_close(bb_conn_t *c);

#ifdef __cplusplus
}
#endif
