[platformio]
src_dir = main

[env:minimal]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-p4-evboard
board_build.chip_variant = esp32p4
framework = espidf
board_build.cmake_extra_args =
    -DFIRMWARE_BOARD=elecrow_p4_hmi7
    -DFIRMWARE_BOARD_elecrow_p4_hmi7=1
monitor_speed = 115200
