[platformio]
src_dir = test

[env:native]
platform = native
test_framework = unity
test_filter = test_host
extra_scripts = pre:scripts/coverage.py
build_flags =
    -O0
    -DUNITY_INCLUDE_DOUBLE
    -Icomponents/log_stream/include
    -Icomponents/http_server/include
    -Icomponents/bb_prov/include
    -Icomponents/ota_pull/include
    -Icomponents/ota_push/include
    -Icomponents/nv_config/include
    -lm
lib_deps = https://github.com/DaveGamble/cJSON.git#v1.7.18
test_build_src = yes
build_src_filter = +<../platform/espidf/log_stream/log_stream.c> +<../components/http_server/src/http_utils.c> +<../components/bb_prov/src/bb_prov_parse.c> +<../platform/espidf/ota_pull/ota_pull.c> +<../platform/espidf/ota_push/ota_push.c> +<../platform/espidf/nv_config/nv_config.c>
