// Portable smoke app — exercises bb_log, bb_settings, bb_wifi, bb_http on every
// supported framework/backend. Entry shims (entry_arduino.cpp / entry_espidf.c)
// call into smoke_app_setup() and smoke_app_loop().
//
// The same source compiles unchanged across all envs in platformio.ini.
// Backend selection happens via build_src_filter and build_flags.

#include "bb_log.h"
#include "bb_config.h"
#include "bb_http.h"
#include "bb_http_server.h"
#include "bb_wifi.h"
#ifdef ESP_PLATFORM
#include "bb_ota_check.h"
#include "bb_ws_server.h"
#include "bb_serialize_console.h"
#include "bb_timer.h"

/* bb_embed_site codegen smoke: accessor generated by bbtool gen-site at configure
 * time from examples/smoke/main/demo_site/.  The table symbol and _get()
 * function are declared here so the compile+link path is exercised on every
 * ESP-IDF board build.  Arduino builds compile this file too but the block
 * below is guarded by ESP_PLATFORM so the Arduino env is unaffected. */
extern bb_http_asset_t demo_site[];
extern const bb_http_asset_t *demo_site_get(size_t *n);
#endif
#include "smoke_app.h"

static const char *TAG = "smoke";

// Boot counter, round-tripped through bb_config (typed layer over
// bb_storage) rather than bb_nv's generic KV forwarder (B1-756, bb_nv
// dissolution epic B1-708) -- BB_CONFIG_U32 resolves to the SAME
// nvs_get_u32/nvs_set_u32 calls bb_nv_get_u32/set_u32 made (both are thin
// forwarders to bb_storage_nvs), so the "app"/"boot" ns/key/U32-typed
// on-flash format is byte-compatible with what this component previously
// read/wrote via bb_nv. has_default/def.u32=0 mirrors bb_nv_get_u32's
// fallback-on-not-found contract explicitly -- bb_config_get_u32 leaves
// *out untouched on a non-BB_OK return unless has_default resolves a
// NOT_FOUND, unlike bb_nv_get_u32 which always writes the fallback.
static const bb_config_field_t s_boot_count_field = {
    .id          = "smoke.app.boot",
    .type        = BB_CONFIG_U32,
    .addr        = { .backend = "nvs", .ns_or_dir = "app", .key = "boot" },
    .def         = { .u32 = 0 },
    .has_default = true,
};

static bb_err_t ping_handler(bb_http_request_t *req) {
    bb_http_resp_set_header(req, "Content-Type", "text/plain");
    bb_http_resp_send_chunk(req, "pong\n", 5);
    bb_http_resp_send_chunk(req, NULL, 0);
    bb_log_i(TAG, "GET /ping -> pong");
    return BB_OK;
}

#ifdef ESP_PLATFORM
// WebSocket echo handler: reflects received TEXT/BINARY frames back to sender.
static bb_err_t ws_echo_handler(bb_http_request_t *req,
                                const bb_ws_server_frame_t *frame)
{
    if (frame->type == BB_WS_TYPE_TEXT || frame->type == BB_WS_TYPE_BINARY) {
        bb_log_i(TAG, "ws: echo %zu bytes", frame->len);
        bb_ws_server_frame_t reply = {
            .final   = true,
            .type    = frame->type,
            .payload = frame->payload,
            .len     = frame->len,
        };
        return bb_ws_server_send_frame(req, &reply);
    }
    return BB_OK;
}

// POST /api/wsbcast: broadcast a text message to all WS clients.
static bb_err_t wsbcast_handler(bb_http_request_t *req)
{
    char buf[128] = {0};
    int len = bb_http_req_recv(req, buf, sizeof(buf) - 1);
    if (len <= 0) {
        return bb_http_resp_no_content(req);
    }
    buf[len] = '\0';

    bb_ws_server_frame_t frame = {
        .final   = true,
        .type    = BB_WS_TYPE_TEXT,
        .payload = (uint8_t *)buf,
        .len     = (size_t)len,
    };
    bb_ws_server_broadcast_all(bb_http_server_get_handle(), &frame, NULL, NULL);
    return bb_http_resp_no_content(req);
}

static const bb_route_response_t s_ws_responses[] = {
    {
        .status      = 101,
        .description = "WebSocket upgrade (Switching Protocols)",
    },
    { .status = 0 },
};

static const bb_route_t s_ws_route = {
    .method       = BB_HTTP_GET,
    .path         = "/ws",
    .tag          = "websocket",
    .summary      = "WebSocket echo endpoint (upgrade via GET; x-protocol: websocket)",
    .operation_id = "wsConnect",
    .responses    = s_ws_responses,
    .handler      = NULL,
};

// Heap baseline interval (ms). Every board in the CI smoke matrix emits this
// line so a heap regression on any target shows up in serial output.
#define BB_SMOKE_HEAP_LOG_INTERVAL_MS 5000

// Heap baseline SOURCE: emitted via bb_serialize_console_heap_report() --
// gather (bb_meminfo) -> render (bb_serialize_walk over
// bb_serialize_console_heap_desc) -> bb_log_i(), all internal to that call.
// Measured, not published — serial only. Runs as a bb_timer MODE-A job on
// the shared bb_timer_disp task — no dedicated task.
static void heap_log_tick(void *arg)
{
    (void)arg;
    bb_serialize_console_heap_report("tick");
}
#endif // ESP_PLATFORM

void smoke_app_setup(void) {
    // bb_settings_creds_boot_init() is codegen-composed (tier=early,
    // components/bb_settings/include/bb_settings.h) and already ran via
    // bb_app_init_early() before smoke_app_setup() is called
    // (examples/smoke/main/entry_espidf.c) -- do not call it again here.
    bb_log_i(TAG, "boot");

    uint32_t boot_count = 0;
    bb_err_t boot_rc = bb_config_get_u32(&s_boot_count_field, &boot_count);
    if (boot_rc != BB_OK) {
        // NOT_FOUND is already resolved to BB_OK via has_default/def.u32
        // above -- a non-BB_OK return here is a genuine backend error
        // (e.g. width/type mismatch), which leaves boot_count untouched.
        // Fall back to the field's own default explicitly rather than
        // relying on the local zero-init to happen to match it.
        bb_log_w(TAG, "boot_count: get failed (%d), using default", (int)boot_rc);
        boot_count = s_boot_count_field.def.u32;
    }
    boot_count++;
    bb_config_set_u32(&s_boot_count_field, boot_count);
    bb_log_i(TAG, "boot=%lu", (unsigned long)boot_count);

    bb_wifi_set_hostname("bb-smoke");
    // WiFi init and HTTP server start are handled by bb_app_init_early()
    // (bb_wifi_autoinit) and bb_app_init() (bb_http_autostart_init)
    // respectively -- the `bbtool codegen`-generated composition root.
    // Route registration still happens here because /ping is not a
    // codegen-composed entry.
    bb_http_register_route(bb_http_server_get_handle(), BB_HTTP_GET, "/ping", ping_handler);

#ifdef ESP_PLATFORM
    // bb_meminfo heap baseline: boot line immediately, then hand off to a
    // bb_timer MODE-A periodic job on the shared bb_timer_disp task.
    heap_log_tick(NULL);
    {
        bb_periodic_timer_t heap_log_timer = NULL;
        bb_err_t herr = bb_timer_deferred_periodic_create(
            heap_log_tick, NULL, "heap_log", &heap_log_timer);
        if (herr == BB_OK) {
            bb_timer_periodic_start(heap_log_timer,
                                    (uint64_t)BB_SMOKE_HEAP_LOG_INTERVAL_MS * 1000ULL);
        } else {
            bb_log_w(TAG, "heap_log: timer create failed (%d)", (int)herr);
        }
    }

    // bb_temp: /api/health "temp" section (present=false on unsupported
    // targets, e.g. classic ESP32) is registered by the codegen-composed
    // bb_temp_autoregister_init() (tier=regular, components/bb_temp/include/
    // bb_temp.h), which already ran via bb_app_init_rest() before
    // smoke_app_setup() is called -- do not call bb_temp_register_info()
    // again here.

    // bb_ota_check: link-load only. No URL set, so polling stays idle and
    // bb_ota_check_now() returns BB_ERR_INVALID_STATE cleanly. Consumers
    // (TaipanMiner, snugfeather) call bb_ota_check_set_releases_url(...).
    if (bb_ota_check_init(NULL) != BB_OK) {
        bb_log_w(TAG, "bb_ota_check: init failed");
    }

    // bb_ws_server: /ws echo + /api/wsbcast broadcast demo.
    {
        bb_http_handle_t svr = bb_http_server_get_handle();
        bb_err_t wserr = bb_ws_server_register_described_endpoint(
            svr, "/ws", ws_echo_handler, &s_ws_route);
        if (wserr == BB_OK) {
            bb_log_i(TAG, "bb_ws_server: /ws registered");
        } else {
            bb_log_w(TAG, "bb_ws_server: /ws register failed (%d)", (int)wserr);
        }
        bb_err_t wsbcast_err = bb_http_register_route(svr, BB_HTTP_POST, "/api/wsbcast",
                                                      wsbcast_handler);
        if (wsbcast_err == BB_OK) {
            bb_log_i(TAG, "bb_ws_server: /api/wsbcast registered");
        } else {
            bb_log_w(TAG, "bb_ws_server: /api/wsbcast register failed (%d)", (int)wsbcast_err);
        }
    }

    // bb_embed_site smoke: register the demo SPA assets to prove the
    // codegen→C→link path compiles correctly on every ESP-IDF board target.
    {
        size_t n = 0;
        const bb_http_asset_t *assets = demo_site_get(&n);
        bb_err_t rc = bb_http_register_assets(bb_http_server_get_handle(), assets, n);
        if (rc == BB_OK) {
            bb_log_i(TAG, "bb_embed_site: registered %u demo_site assets", (unsigned)n);
        } else {
            bb_log_w(TAG, "bb_embed_site: register_assets failed (%d)", (int)rc);
        }
    }
#endif
}

void smoke_app_loop(void) {
    bb_http_server_poll();
}
