"""embed command — convert a single file to a gzipped C byte-array source file.

CLI contract:
    bbtool embed <in> <out> <symbol>

    in      — path to the source file (read as binary)
    out     — path for the generated .c file (parent dir must exist)
    symbol  — C identifier used for the byte-array and length constant

The generated file declares:
    const uint8_t  <symbol>[];
    const size_t   <symbol>_len;

Bytes are gzip-compressed (level 9, mtime=0 for reproducible output).
Encoding/mime declarations are the consumer's responsibility.

CLI progress → stdout.

Importable API:
    embed_file(in, out, symbol)  — same logic; progress → stderr.
"""
from __future__ import annotations

import gzip
import io
import os
import sys

NAME = "embed"
HELP = "Embed a binary file as a gzipped C byte-array"


def add_arguments(parser) -> None:
    parser.add_argument("input", help="path to the source file")
    parser.add_argument("output", help="path for the generated .c file")
    parser.add_argument("symbol", help="C identifier for the byte-array and length")


def run(args) -> int:
    _embed(args.input, args.output, args.symbol, _progress_to_stderr=False)
    return 0


# ---------------------------------------------------------------------------
# Importable API (used by gen_site command; progress → stderr so cmake
# execute_process OUTPUT_VARIABLE captures only intended output)
# ---------------------------------------------------------------------------

def embed_file(input_path: str, output_c_path: str, symbol_name: str) -> None:
    """Read input_path, gzip-compress it, write a C source file to output_c_path.

    Progress message goes to stderr. Calls sys.exit(1) on read/write errors.
    """
    _embed(input_path, output_c_path, symbol_name, _progress_to_stderr=True)


# ---------------------------------------------------------------------------
# Implementation
# ---------------------------------------------------------------------------

def _embed(input_path: str, output_c_path: str, symbol_name: str,
           _progress_to_stderr: bool = False) -> None:
    """Read input_path, gzip-compress it, write a C source file to output_c_path."""
    _progress_out = sys.stderr if _progress_to_stderr else sys.stdout

    try:
        with open(input_path, "rb") as f:
            raw = f.read()
    except OSError as e:
        print(f"embed_html: error reading {input_path}: {e}", file=sys.stderr)
        sys.exit(1)

    bio = io.BytesIO()
    with gzip.GzipFile(fileobj=bio, mode="wb", mtime=0) as gz:
        gz.write(raw)
    data = bio.getvalue()

    basename = os.path.basename(input_path)

    lines = [
        "// Auto-generated by breadboard/scripts/embed_html.py — do not edit.",
        f"// Source: {basename}",
        "#include <stddef.h>",
        "#include <stdint.h>",
        f"const uint8_t {symbol_name}[] = {{",
    ]

    # 16 bytes per line
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    lines += [
        "};",
        f"const size_t {symbol_name}_len = sizeof({symbol_name});",
    ]

    try:
        with open(output_c_path, "w") as f:
            f.write("\n".join(lines) + "\n")
    except OSError as e:
        print(f"embed_html: error writing {output_c_path}: {e}", file=sys.stderr)
        sys.exit(1)

    print(
        f"embed_html: {basename} -> {output_c_path} "
        f"({len(raw)} bytes -> {len(data)} bytes compressed)",
        file=_progress_out,
    )
