"""verify-generated command (B1-1371) -- build-time staleness guard for a
gitignored `bbtool codegen` output file (`bb_app_init.c`).

**The defect this closes.** `bb_app_init.c` is generated, gitignored, and
regenerated by the explicit `make smoke-gen*`/`floor-gen` targets -- never by
the CMake/PlatformIO build itself. A plain `pio run`/`make floor` (see
`examples/floor/main/CMakeLists.txt`: no `floor-gen` prerequisite) happily
compiles whatever `generated/bb_app_init.c` already sits on disk, even if it
was rendered against an EARLIER checkout's `// bbtool:init` marker set. A
stale copy can therefore reach a flashed firmware image with no build-time
signal at all -- confirmed on hardware (B1-1371): a stale `bb_app_init.c`
called `bb_health_reserve_routes()`, a function long deleted from every
header in the tree, and called `bb_health_init()` before the health-section
autoregister calls it now (correctly) follows.

**Mechanism chosen: call-site symbol existence, not a full re-resolve.**
Re-running the whole `wire`/`composition` pipeline at every CMake configure
would be the fully sound fix (see the module docstring trade-off below), but
at the time this check was added that meant codegen becoming a build-graph
step instead of an explicit `make *-gen` target -- a restructuring of how
codegen is invoked, out of scope for THIS ticket (B1-1371). Cheaper and
still real: parse every function CALLED in the generated file and confirm
each one is still declared SOMEWHERE in the current tree. `// bbtool:init
fn=<name>` markers live in the SAME public header as the function's own
prototype (see `commands.wire`'s module docstring), so a real, live
composition always has a matching declaration to find; a symbol with no
declaration anywhere is proof the generated call target no longer exists in
current source -- exactly the `bb_health_reserve_routes()` case above.

**What this does NOT catch (closed separately, B1-1403).** A stale file
whose called functions still all exist in the CURRENT tree -- e.g. a pure
ORDERING regression (the `bb_health_init()`-before-autoregister half of the
same incident) -- is invisible to THIS check: nothing here re-derives the
correct tier order or diffs it against what the file actually emits. B1-1403
closes that remaining gap the way this docstring originally flagged as
out-of-scope: `cmake/bb_generated.cmake`'s `bb_regenerate_wire_or_fail` now
runs `bbtool codegen` itself at every real-pass CMake configure, so
`bb_app_init.c` is unconditionally regenerated from the CURRENT marker set
rather than merely checked for staleness. An ordering regression can no
longer survive a configure pass that actually runs -- which the example
CMakeLists.txt call sites' `CMAKE_CONFIGURE_DEPENDS` registration (every
component/platform header AND CMakeLists.txt, the bbtool sources, and
bbtool.toml) makes happen on every codegen-input change, not just when the
CMakeLists.txt itself is touched. This symbol-existence check remains as
cheap belt-and-braces defense-in-depth: it still catches a codegen bug in
the regeneration itself, a hand-edit of the generated file after configure,
or any future path that writes `bb_app_init.c` out-of-band without going
through `bb_regenerate_wire_or_fail`.
"""
from __future__ import annotations
import argparse
import glob
import os
import re
import sys
from typing import List, Set, Tuple

NAME = "verify-generated"
HELP = ("verify-generated: hard-fail if a generated bb_app_init.c calls a symbol no "
        "longer declared anywhere in the tree (stale-artifact guard, B1-1371)")

# C keywords that can appear directly followed by '(' in the generated file's
# own control-flow (`if (...)`) -- never a real call target.
_KEYWORDS = frozenset({"if", "else", "for", "while", "switch", "return", "sizeof", "defined"})

# The three functions the generated file DEFINES itself (never a symbol some
# OTHER header must declare) -- both the definition line
# ("bb_err_t bb_app_init_early(void)") and the internal
# bb_app_init_early()/bb_app_init_rest() calls inside bb_app_init()'s own
# body match the call regex below and must be excluded here.
_SELF_DEFINED = frozenset({"bb_app_init_early", "bb_app_init_rest", "bb_app_init"})

_CALL_RE = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(")

# Matches a whole `/* ... */` block, single- or multi-line, non-greedy so a
# `/* a */ code /* b */` line doesn't swallow the code between the two
# comments as part of one match.
_BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)


def _blank_block_comments(text: str) -> str:
    """Replaces every `/* ... */` block (including its OPENING line, whether
    that line is comment-only or starts mid-line after real code) with
    whitespace, preserving every newline so line numbers in the caller's
    per-line scan stay accurate. A single-line `/* foo() */` and a
    multi-line block whose first line reads `/* note: foo() */` are both
    fully blanked this way, not just their `*`-prefixed continuation lines.
    Does not understand string literals -- a `/*`/`*/` pair inside a string
    would be (mis)matched like a real comment. Soundness here relies on the
    codegen templates that produce this file's input never emitting `/*`
    or `*/` inside a string literal, not on this being a real C tokenizer."""
    return _BLOCK_COMMENT_RE.sub(lambda m: "".join(ch if ch == "\n" else " " for ch in m.group(0)), text)

# Trees searched for a matching declaration. `examples/` is included (not
# just components/platform) since a --consumer-manifest marker (e.g.
# examples/smoke/main/bb_wire.h) can be the ONLY place a symbol used by a
# manifest-only wiring detail is declared.
_DECLARATION_GLOBS = ("components/**/*.h", "platform/**/*.h", "examples/**/*.h")

_EXCLUDE_DIR_NAMES = frozenset({".git", ".pio", "generated", "__pycache__"})


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--root", default=None, help="repository root (default: from top-level --root or cwd)")
    parser.add_argument(
        "--file", required=True,
        help="path to the generated bb_app_init.c to verify (relative to --root, or absolute)",
    )


def extract_called_symbols(text: str) -> List[Tuple[int, str]]:
    """Returns `(lineno, symbol)` pairs for every apparent function-call
    target in `text` — one entry per regex match, duplicates included (the
    caller only needs the *set* of distinct offenders, but keeping every
    occurrence lets the error message point at the first offending line for
    a given symbol). `/* ... */` block comments -- single-line, multi-line,
    and mid-line-opening alike -- are blanked out over the WHOLE text first
    (see `_blank_block_comments`), so a call-shaped symbol mentioned only in
    a block comment is never extracted, regardless of which physical line of
    the block it sits on. After that, skips `#include`/`#define` lines and
    whole lines that start with `//` (a leftover `*`-prefixed continuation
    line is also skipped, though block-stripping already blanks those).
    A `// ...` comment trailing real code on the same line is NOT stripped
    -- a call-shaped mention there would still be (mis)extracted; this
    function only closes the block-comment gap. Drops both C keywords and
    the file's own three self-defined function names (see module docstring)
    from the matches."""
    text = _blank_block_comments(text)
    results: List[Tuple[int, str]] = []
    for lineno, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped[0] in "#*" or stripped.startswith("//"):
            continue
        for m in _CALL_RE.finditer(line):
            name = m.group(1)
            if name in _KEYWORDS or name in _SELF_DEFINED:
                continue
            results.append((lineno, name))
    return results


def _declared_symbols(root: str) -> Set[str]:
    """Every identifier immediately followed by '(' across every `.h` file
    under `_DECLARATION_GLOBS`, excluding `_EXCLUDE_DIR_NAMES` path
    components (mirrors this repo's usual host-tooling exclusion set). A raw
    grep, not a real C parser -- same posture as `wire_parse.py`'s own marker
    scan ("no preprocessor is involved"): a declaration inside a disabled
    `#if 0` block or a comment is indistinguishable from a live one here, so
    this check is deliberately permissive (never flags a symbol that merely
    moved headers or is currently comment-fenced) at the cost of a
    theoretical false negative for a symbol whose only remaining textual
    trace is dead/commented-out -- acceptable since the failure mode this
    guards against is a symbol with NO trace anywhere, not a subtly-disabled
    one."""
    declared: Set[str] = set()
    for pattern in _DECLARATION_GLOBS:
        for path in glob.glob(os.path.join(root, pattern), recursive=True):
            parts = set(path.split(os.sep))
            if parts & _EXCLUDE_DIR_NAMES:
                continue
            try:
                with open(path, encoding="utf-8", errors="replace") as f:
                    text = f.read()
            except OSError:
                continue
            declared.update(m.group(1) for m in _CALL_RE.finditer(text))
    return declared


def run(args: argparse.Namespace) -> int:
    root = os.path.abspath(getattr(args, "root", None) or getattr(args, "_root_abs", None) or os.getcwd())
    file_arg = args.file
    file_path = file_arg if os.path.isabs(file_arg) else os.path.join(root, file_arg)

    if not os.path.isfile(file_path):
        print(f"bbtool verify-generated: error: {file_path} does not exist", file=sys.stderr)
        return 1

    with open(file_path, encoding="utf-8", errors="replace") as f:
        text = f.read()

    called = extract_called_symbols(text)
    if not called:
        print(f"bbtool verify-generated: {file_path}: no call sites found -- OK")
        return 0

    declared = _declared_symbols(root)

    seen_missing: dict = {}
    for lineno, name in called:
        if name in declared:
            continue
        seen_missing.setdefault(name, lineno)

    if seen_missing:
        detail = "; ".join(
            f"{file_path}:{lineno}: '{name}'" for name, lineno in sorted(seen_missing.items(), key=lambda kv: kv[1])
        )
        print(
            "bbtool verify-generated: error: "
            f"{file_path} calls symbol(s) with no matching declaration anywhere under "
            "components/, platform/, or examples/ -- this is a STALE generated artifact "
            "(regenerate via the matching `make *-gen` target before building): "
            f"{detail}",
            file=sys.stderr,
        )
        return 1

    print(f"bbtool verify-generated: {file_path}: {len(set(n for _, n in called))} referenced symbol(s) all declared -- OK")
    return 0


def register(api) -> None:
    api.add_command(NAME, sys.modules[__name__])
