[platformio]
default_envs = uno

[env:uno]
platform = atmelavr@5.1.0
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/adafruit/Adafruit_CC3000_Library.git
build_flags =
    -I../../components/log_stream/include
    -I../../components/nv_config/include
    -Iinclude
build_src_filter =
    +<*>
    +<../../../platform/arduino/log_stream/*.cpp>
    +<../../../platform/arduino/nv_config/*.cpp>

; macOS ARM64: uncomment and update username if using Homebrew toolchain
; platform_packages =
;     toolchain-atmelavr@symlink:///Users/username/.local/pio-avr
;     tool-avrdude@symlink:///Users/username/.local/pio-avrdude
