"""verify-generated command tests (B1-1371) -- stale-artifact guard for a
generated bb_app_init.c: parses call targets and hard-fails if any of them
has no matching declaration anywhere under components/, platform/, or
examples/."""
import argparse
import contextlib
import io
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "commands"))

from commands import verify_generated as vg
from commands.verify_generated import extract_called_symbols, register, run


class TestExtractCalledSymbols(unittest.TestCase):
    def test_extracts_plain_call(self):
        text = "    bb_app_rc = bb_health_stack_monitor_start();\n"
        self.assertEqual(extract_called_symbols(text), [(1, "bb_health_stack_monitor_start")])

    def test_extracts_nested_args_call(self):
        text = "    bb_app_rc = bb_wifi_prov_autoinit(bb_wifi_prov_default_form_get(),1,NULL);\n"
        result = extract_called_symbols(text)
        names = [n for _, n in result]
        self.assertIn("bb_wifi_prov_autoinit", names)
        self.assertIn("bb_wifi_prov_default_form_get", names)

    def test_extracts_consumes_call(self):
        text = "    bb_cache_set_source(bb_wifi_source, NULL);\n"
        self.assertEqual(extract_called_symbols(text), [(1, "bb_cache_set_source")])

    def test_extracts_http_handle_capture(self):
        text = "    __auto_type bb_app_http_handle = bb_http_server_start();\n"
        self.assertEqual(extract_called_symbols(text), [(1, "bb_http_server_start")])

    def test_skips_include_lines(self):
        text = '#include "bb_health.h"\n'
        self.assertEqual(extract_called_symbols(text), [])

    def test_skips_define_lines(self):
        text = '#define BB_APP_INIT_TAG "bb_app_init"\n'
        self.assertEqual(extract_called_symbols(text), [])

    def test_skips_comment_lines(self):
        text = "/* Generated by `bbtool codegen` -- DO NOT EDIT. */\n * more comment(text)\n"
        self.assertEqual(extract_called_symbols(text), [])

    def test_skips_line_comment(self):
        text = "// some_fn(x) in a line comment\n"
        self.assertEqual(extract_called_symbols(text), [])

    def test_skips_keywords(self):
        text = "    if (bb_app_avail_wifi && bb_app_avail_mqtt) {\n"
        self.assertEqual(extract_called_symbols(text), [])

    def test_skips_self_defined_functions(self):
        text = (
            "bb_err_t bb_app_init_early(void)\n"
            "{\n"
            "bb_err_t bb_app_init(void)\n"
            "{\n"
            "    bb_err_t bb_app_first_err = bb_app_init_early();\n"
            "    bb_err_t bb_app_rest_err = bb_app_init_rest();\n"
        )
        self.assertEqual(extract_called_symbols(text), [])

    def test_blank_line_yields_nothing(self):
        self.assertEqual(extract_called_symbols("\n   \n"), [])

    def test_skips_single_line_block_comment_call(self):
        # A single-line `/* ... foo_bar() ... */` comment must not surface
        # its call-shaped mention as a real call.
        text = "    /* note: previously called bb_health_reserve_routes() here */\n"
        self.assertEqual(extract_called_symbols(text), [])

    def test_skips_multiline_block_comment_opening_line_call(self):
        # The OPENING line of a multi-line block comment can itself contain
        # a call-shaped mention (only `*`-prefixed continuation lines were
        # previously skipped) -- it must not be extracted either.
        text = (
            "    /* note: previously called bb_health_reserve_routes() here\n"
            "     * removed in a later refactor\n"
            "     */\n"
        )
        self.assertEqual(extract_called_symbols(text), [])

    def test_extracts_real_call_but_not_mid_line_block_comment_call(self):
        # A block comment opening mid-line, after real code: the real call
        # must still be extracted, the commented-out one must not.
        text = "    bb_app_rc = bb_foo_init(); /* was bb_health_reserve_routes() */\n"
        self.assertEqual(extract_called_symbols(text), [(1, "bb_foo_init")])

    def test_extracts_genuine_call_on_normal_line(self):
        # Regression: a genuine call on a plain code line is still
        # extracted -- guards against an over-broad comment strip that
        # would silently neuter the whole check.
        text = "    bb_app_rc = bb_health_stack_monitor_start();\n"
        self.assertEqual(extract_called_symbols(text), [(1, "bb_health_stack_monitor_start")])


class _TestTreeMixin:
    def _make_tree(self, generated_body: str):
        tmp = tempfile.mkdtemp()
        header_dir = os.path.join(tmp, "components", "bb_foo", "include")
        os.makedirs(header_dir)
        with open(os.path.join(header_dir, "bb_foo.h"), "w", encoding="utf-8") as f:
            f.write(
                "#pragma once\n"
                "// bbtool:init tier=regular fn=bb_foo_init\n"
                "bb_err_t bb_foo_init(void);\n"
            )
        gen_dir = os.path.join(tmp, "examples", "smoke", "main", "generated")
        os.makedirs(gen_dir)
        gen_path = os.path.join(gen_dir, "bb_app_init.c")
        with open(gen_path, "w", encoding="utf-8") as f:
            f.write(generated_body)
        return tmp, gen_path


class TestRun(_TestTreeMixin, unittest.TestCase):
    def _run(self, root, file_path):
        args = argparse.Namespace(root=root, file=file_path)
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            rc = run(args)
        return rc, out.getvalue(), err.getvalue()

    def test_missing_file_is_error(self):
        tmp = tempfile.mkdtemp()
        rc, _out, err = self._run(tmp, os.path.join(tmp, "nope.c"))
        self.assertEqual(rc, 1)
        self.assertIn("does not exist", err)

    def test_all_symbols_declared_passes(self):
        body = (
            "/* Generated by `bbtool codegen` -- DO NOT EDIT, DO NOT COMMIT. */\n"
            '#include "bb_foo.h"\n\n'
            "bb_err_t bb_app_init_early(void)\n{\n"
            "    bb_err_t bb_app_first_err = BB_OK;\n"
            "    bb_err_t bb_app_rc;\n\n"
            "    bb_app_rc = bb_foo_init();\n"
            "    return bb_app_first_err;\n}\n"
        )
        tmp, gen_path = self._make_tree(body)
        rc, out, _err = self._run(tmp, gen_path)
        self.assertEqual(rc, 0)
        self.assertIn("all declared -- OK", out)

    def test_no_call_sites_passes(self):
        tmp, gen_path = self._make_tree("/* nothing to call */\n")
        rc, out, _err = self._run(tmp, gen_path)
        self.assertEqual(rc, 0)
        self.assertIn("no call sites found", out)

    def test_deleted_symbol_call_fails(self):
        # Mirrors the real B1-1371 incident: a stale generated file calling
        # a function (bb_health_reserve_routes) that no longer exists in any
        # header in the tree.
        body = (
            "bb_err_t bb_app_init_early(void)\n{\n"
            "    bb_err_t bb_app_first_err = BB_OK;\n"
            "    bb_err_t bb_app_rc;\n\n"
            "    bb_app_rc = bb_foo_init();\n"
            "    bb_app_rc = bb_health_reserve_routes();\n"
            "    return bb_app_first_err;\n}\n"
        )
        tmp, gen_path = self._make_tree(body)
        rc, _out, err = self._run(tmp, gen_path)
        self.assertEqual(rc, 1)
        self.assertIn("bb_health_reserve_routes", err)
        self.assertIn("STALE generated artifact", err)
        # A still-declared symbol on the same file must not also be flagged.
        self.assertNotIn("'bb_foo_init'", err)

    def test_relative_file_path_resolves_against_root(self):
        body = "bb_err_t bb_app_init_early(void)\n{\n    bb_app_rc = bb_foo_init();\n}\n"
        tmp, gen_path = self._make_tree(body)
        rel = os.path.relpath(gen_path, tmp)
        rc, _out, _err = self._run(tmp, rel)
        self.assertEqual(rc, 0)

    def test_falls_back_to_root_abs_when_root_unset(self):
        body = "bb_err_t bb_app_init_early(void)\n{\n    bb_app_rc = bb_foo_init();\n}\n"
        tmp, gen_path = self._make_tree(body)
        rel = os.path.relpath(gen_path, tmp)
        args = argparse.Namespace(root=None, file=rel, _root_abs=tmp)
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            rc = run(args)
        self.assertEqual(rc, 0)


class TestRegister(unittest.TestCase):
    def test_register_adds_command(self):
        added = {}

        class FakeApi:
            def add_command(self, name, mod):
                added[name] = mod

        register(FakeApi())
        self.assertEqual(added, {vg.NAME: vg})


if __name__ == "__main__":
    unittest.main()
