"""embed command tests."""
import argparse
import gzip
import io
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "commands"))

from commands.embed import embed_file, _embed, run


def _golden_gzip(data: bytes) -> bytes:
    """Produce the canonical gzip bytes: level 9, mtime=0."""
    bio = io.BytesIO()
    with gzip.GzipFile(fileobj=bio, mode="wb", mtime=0) as gz:
        gz.write(data)
    return bio.getvalue()


class TestEmbedFile(unittest.TestCase):
    """embed_file() produces a valid .c file."""

    def test_creates_output_file(self):
        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "hello.html")
            out = os.path.join(td, "hello.c")
            with open(src, "wb") as f:
                f.write(b"<html>hello</html>")
            embed_file(src, out, "test_sym")
            self.assertTrue(os.path.isfile(out))

    def test_output_contains_symbol(self):
        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "hello.html")
            out = os.path.join(td, "hello.c")
            with open(src, "wb") as f:
                f.write(b"<html>hello</html>")
            embed_file(src, out, "my_symbol")
            content = open(out).read()
            self.assertIn("const uint8_t my_symbol[]", content)
            self.assertIn("const size_t my_symbol_len", content)

    def test_output_contains_auto_generated_comment(self):
        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "x.html")
            out = os.path.join(td, "x.c")
            with open(src, "wb") as f:
                f.write(b"x")
            embed_file(src, out, "s")
            content = open(out).read()
            self.assertIn("Auto-generated by bbtool embed", content)

    def test_output_contains_source_filename(self):
        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "myfile.html")
            out = os.path.join(td, "myfile.c")
            with open(src, "wb") as f:
                f.write(b"content")
            embed_file(src, out, "sym")
            content = open(out).read()
            self.assertIn("// Source: myfile.html", content)

    def test_byte_parity_gzip(self):
        """Output hex bytes must decode to canonical gzip of the input."""
        raw = b"hello breadboard"
        expected_gz = _golden_gzip(raw)

        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "in.bin")
            out = os.path.join(td, "out.c")
            with open(src, "wb") as f:
                f.write(raw)
            embed_file(src, out, "sym")

            # Parse hex bytes from the .c output (inside the with block)
            content = open(out).read()
            hex_bytes = []
            for line in content.splitlines():
                line = line.strip()
                if line.startswith("0x") or (", 0x" in line):
                    for token in line.split(","):
                        token = token.strip().rstrip(",")
                        if token.startswith("0x"):
                            hex_bytes.append(int(token, 16))
            actual_gz = bytes(hex_bytes)
        self.assertEqual(actual_gz, expected_gz,
                         "gzip output must be byte-identical to mtime=0 level-9 gzip")

    def test_mtime_zero_reproducible(self):
        """Two calls on the same input must produce identical output."""
        raw = b"reproducible"
        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "in.bin")
            out1 = os.path.join(td, "out1.c")
            out2 = os.path.join(td, "out2.c")
            with open(src, "wb") as f:
                f.write(raw)
            embed_file(src, out1, "sym")
            embed_file(src, out2, "sym")
            self.assertEqual(open(out1).read(), open(out2).read())

    def test_16_bytes_per_line(self):
        """Hex data must appear 16 bytes per row."""
        raw = bytes(range(32))  # exactly 2 rows of 16
        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "in.bin")
            out = os.path.join(td, "out.c")
            with open(src, "wb") as f:
                f.write(raw)
            embed_file(src, out, "sym")
            content = open(out).read()
        data_lines = [
            ln.strip() for ln in content.splitlines()
            if ln.strip().startswith("0x")
        ]
        for ln in data_lines:
            count = ln.count("0x")
            self.assertLessEqual(count, 16, f"row has more than 16 bytes: {ln}")

    def test_missing_input_exits(self):
        with tempfile.TemporaryDirectory() as td:
            out = os.path.join(td, "out.c")
            with self.assertRaises(SystemExit) as cm:
                embed_file(os.path.join(td, "nonexistent.html"), out, "sym")
            self.assertNotEqual(cm.exception.code, 0)


class TestEmbedRun(unittest.TestCase):
    """run() dispatches correctly."""

    def test_run_returns_zero(self):
        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "a.html")
            out = os.path.join(td, "a.c")
            with open(src, "wb") as f:
                f.write(b"<html/>")
            args = argparse.Namespace(input=src, output=out, symbol="sym_a")
            rc = run(args)
            self.assertEqual(rc, 0)

    def test_run_creates_file(self):
        with tempfile.TemporaryDirectory() as td:
            src = os.path.join(td, "b.html")
            out = os.path.join(td, "b.c")
            with open(src, "wb") as f:
                f.write(b"<html/>")
            args = argparse.Namespace(input=src, output=out, symbol="sym_b")
            run(args)
            self.assertTrue(os.path.isfile(out))


if __name__ == "__main__":
    unittest.main()
