#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include "bb_wifi.h"

// WIFI_RECONN_CONNECTING_TIMEOUT_MS (the WR_CONNECTING watchdog) now lives in
// components/bb_wifi/wifi_reconn_policy.h -- the host-compilable TU that owns
// the FSM table's WR_CONNECTING on_entry hook, which is what arms it
// (B1-805 slice 1a, R8).

// BB_WIFI_INACTIVE_TIME_ENABLE: bridge Kconfig opt-in; default 0 on host.
#ifdef ESP_PLATFORM
#  ifdef CONFIG_BB_WIFI_INACTIVE_TIME_ENABLE
#    define BB_WIFI_INACTIVE_TIME_ENABLE 1
#  endif
#endif
#ifndef BB_WIFI_INACTIVE_TIME_ENABLE
#define BB_WIFI_INACTIVE_TIME_ENABLE 0
#endif

// BB_WIFI_INACTIVE_TIME_S: bridged from Kconfig; falls back to 45 s.
#ifdef ESP_PLATFORM
#  ifdef CONFIG_BB_WIFI_INACTIVE_TIME_S
#    define BB_WIFI_INACTIVE_TIME_S CONFIG_BB_WIFI_INACTIVE_TIME_S
#  endif
#endif
#ifndef BB_WIFI_INACTIVE_TIME_S
#define BB_WIFI_INACTIVE_TIME_S 45U
#endif

// BB_WIFI_RECOVERY_COOLDOWN_S: bridged from Kconfig; falls back to 60 s.
#ifdef ESP_PLATFORM
#  ifdef CONFIG_BB_WIFI_RECOVERY_COOLDOWN_S
#    define BB_WIFI_RECOVERY_COOLDOWN_S CONFIG_BB_WIFI_RECOVERY_COOLDOWN_S
#  endif
#endif
#ifndef BB_WIFI_RECOVERY_COOLDOWN_S
#define BB_WIFI_RECOVERY_COOLDOWN_S 60U
#endif

// Start the reconnect manager (FSM + task). Idempotent. Called from
// bb_wifi_autoinit for BOTH the creds-present and no-creds cases (B1-805
// slice 1a) -- always-create the task so a later EV_CREDS_ARRIVED (posted by
// provisioning) can move a parked WR_NO_CREDS instance to WR_CONNECTING.
// has_creds selects the FSM's initial state: true -> WR_CONNECTING (the
// caller issues the actual first esp_wifi_connect() separately -- this only
// arms the CONNECTING watchdog); false -> WR_NO_CREDS (parked, no timer).
void wifi_reconn_start(bool has_creds);

// True once the manager task is running. The WiFi event handler uses
// this to decide whether to delegate disconnect/got-ip events.
bool wifi_reconn_is_active(void);

// Non-blocking notifiers. Post to the manager's queue and return.
// Safe to call from the WiFi event task context. Drop on full queue.
void wifi_reconn_on_disconnect(uint8_t reason);
void wifi_reconn_on_got_ip(void);

// Lock-free diagnostic reads of manager-owned state.
void wifi_reconn_get_disconnect(bb_wifi_disc_reason_t *reason, int64_t *age_us);
int  wifi_reconn_get_retry_count(void);
void wifi_reconn_get_histogram(uint16_t *out, size_t len);

// LOG-ONLY (B1-805 slice 1a, R11): IP_EVENT_STA_LOST_IP is a 120s-debounced,
// Espressif-documented "generally ignore, it's a debug event" -- NOT a
// disconnect signal. Does not mutate policy state, does not force a
// disconnect/reconnect. WIFI_EVENT_STA_DISCONNECTED (wifi_reconn_on_disconnect)
// is the SOLE authoritative disconnect trigger. Safe to call from the WiFi
// event task context.
void wifi_reconn_on_lost_ip(void);

// Diagnostic counters (lock-free reads of manager-owned state).
uint32_t wifi_reconn_get_lost_ip_count(void);
int64_t  wifi_reconn_get_lost_ip_age_us(void);

// Set s_self_disconnect so the next WIFI_EVENT_STA_DISCONNECTED is absorbed
// without triggering the reconnect FSM. Call before esp_wifi_stop() in a
// controlled restart to absorb the synthetic disconnect it generates.
void wifi_reconn_absorb_next_disconnect(void);

// Diagnostic counter: times the egress probe declared the gateway unreachable
// and called bb_wifi_restart_sta (lock-free read of manager-owned state).
uint32_t wifi_reconn_get_egress_dead_count(void);

// B1-805 slice 1a (R4): a no-op under the bb_fsm reconn. The egress-recovery
// tier-2 path (bb_net_health, CONFIG_BB_NET_HEALTH_EGRESS_ACT_ENABLE) is the
// only caller, and that gate is default-OFF; wifi_reconn.c #errors at
// compile time if it is ever enabled, so this stays inert (never silently
// stale) until the FSM integration lands in slice 1b.
void wifi_reconn_request_recovery(const char *reason);

// Internal accessor (bb_wifi.c) for the injected OTA-image-validated callback
// (bb_wifi_set_ota_validated_cb, bb_wifi.h). DEFAULT true when no callback is
// injected — see bb_wifi.h for rationale. Generated by the bb_core
// BB_CALLBACK_SLOT_RET macro, instantiated in
// platform/host/bb_wifi/bb_wifi_emit.c. Private to this component; not a
// public API.
bool bb_wifi_internal_ota_validated(void);

// Internal invoke (bb_wifi_publish_net_event below) for the generic emit
// seam (bb_wifi_set_emit, bb_wifi.h, PR3 bus-shaping). Null-safe: no-op if
// no sink is registered. Generated by the bb_core BB_CALLBACK_SLOT_VOID
// macro, instantiated in platform/host/bb_wifi/bb_wifi_emit.c. Private to
// this component; not a public API.
void bb_wifi_emit_invoke(const char *topic, int32_t id, const void *payload, size_t size);

// Internal helper (bb_wifi.c's event_handler + bb_wifi_emit_baseline), both
// compiled in platform/host/bb_wifi/bb_wifi_emit.c: builds the wifi.net
// payload (bb_wifi_event_payload_build) and fires it via bb_wifi_emit_invoke
// above. Private to this component; not a public API -- the public entry
// points are bb_wifi_set_emit (register a sink) and bb_wifi_emit_baseline
// (one-shot current-state synthesis), both in bb_wifi.h.
void bb_wifi_publish_net_event(bb_wifi_net_event_t evt, bb_wifi_disc_reason_t reason);
