[platformio]
default_envs = uno_r4_wifi
extra_configs = platformio_local.ini

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
build_flags =
    -DBB_WIFI_BACKEND_R4
    -I../../components/bb_core/include
    -I../../components/bb_log/include
    -I../../components/bb_nv/include
    -I../../components/bb_http/include
    -I../../components/bb_json/include
    -I../../components/bb_ntp/include
    -I../../components/bb_wifi/include
    -I../../components/bb_system/include
    -Iinclude
build_src_filter =
    +<*>
    +<../../../platform/arduino/bb_log/*.cpp>
    +<../../../platform/arduino/bb_nv/*.cpp>
    +<../../../platform/arduino/bb_http/*.cpp>
    +<../../../platform/arduino/bb_json/*.cpp>
    +<../../../platform/arduino/bb_ntp/*.cpp>
    +<../../../platform/arduino/bb_wifi/*.cpp>
    +<../../../platform/arduino/system/*.cpp>
