"""
bb_version.py — PlatformIO pre-script that writes a generated C header containing
the firmware version string.

Precedence (highest → lowest):
  1. BB_FW_VERSION env var (non-empty)  → used verbatim
  2. Consumer repo has an exact git tag at HEAD  → use that tag
  3. dev default: dev-g<consumer_short_sha>[-dirty]-bb-g<bb_short_sha>[-dirty]

The header is written to <PROJECT_DIR>/.breadboard/gen/bb_version_gen.h and
contains:  #define BB_FW_VERSION_STR "<string>"

Only rewritten when the content changes to avoid spurious recompiles.

Consumers must add the generated header directory to their include path:
  build_flags = -I${PROJECT_DIR}/.breadboard/gen
"""

Import("env")

import inspect
import os
import subprocess

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _run_git(args, cwd):
    """Run a git subcommand in cwd; return stripped stdout or '' on any error."""
    try:
        result = subprocess.run(
            ["git"] + args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except Exception:
        return ""


def _short_sha(cwd):
    return _run_git(["rev-parse", "--short=7", "HEAD"], cwd)


def _is_dirty(cwd):
    return bool(_run_git(["status", "--porcelain"], cwd))


def _exact_tag(cwd):
    """Return the exact tag at HEAD, or '' if none."""
    return _run_git(["describe", "--tags", "--exact-match", "HEAD"], cwd)


def _compute_version(consumer_dir, bb_dir):
    """Compute version string according to precedence rules."""

    # 1. User override
    override = os.environ.get("BB_FW_VERSION", "")
    if override:
        return override

    # 2. Exact tag at consumer HEAD
    tag = _exact_tag(consumer_dir)
    if tag:
        return tag

    # 3. Dev default
    consumer_sha = _short_sha(consumer_dir)
    bb_sha = _short_sha(bb_dir)

    if not consumer_sha and not bb_sha:
        return "dev-unknown"

    parts = ["dev"]

    if consumer_sha:
        suffix = "-dirty" if _is_dirty(consumer_dir) else ""
        parts.append(f"g{consumer_sha}{suffix}")
    else:
        parts.append("gunknown")

    parts.append("bb")

    if bb_sha:
        suffix = "-dirty" if _is_dirty(bb_dir) else ""
        parts.append(f"g{bb_sha}{suffix}")
    else:
        parts.append("gunknown")

    return "-".join(parts)


def _write_if_changed(path, content):
    """Write content to path only when it differs from the existing file."""
    try:
        with open(path) as fh:
            if fh.read() == content:
                return False
    except OSError:
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)
    return True


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

# Consumer repo = PlatformIO project dir
consumer_dir = env.subst("$PROJECT_DIR")

# breadboard repo = the directory containing this script (resolve symlinks so
# it works whether .breadboard is a symlink or a real directory).
# `__file__` isn't set when SCons exec()'s the script — use inspect to recover
# the absolute path from the current frame's code-object filename.
_script_path = os.path.abspath(inspect.currentframe().f_code.co_filename)
script_dir = os.path.dirname(os.path.realpath(_script_path))
bb_dir = os.path.abspath(os.path.join(script_dir, ".."))

version = _compute_version(consumer_dir, bb_dir)

header_dir = os.path.join(consumer_dir, ".breadboard", "gen")
header_path = os.path.join(header_dir, "bb_version_gen.h")

content = (
    "/* Auto-generated by scripts/bb_version.py — do not edit */\n"
    "#pragma once\n"
    f'#define BB_FW_VERSION_STR "{version}"\n'
)

changed = _write_if_changed(header_path, content)
status = "updated" if changed else "unchanged"
print(f"bb_version: {version} ({status})")

# Inject the generated directory into the build include path so consumer
# C files can use #if __has_include("bb_version_gen.h")
env.Append(CPPPATH=[header_dir])
