"""embed_html.py — convert a single HTML (or any binary) file to a gzipped C byte-array source file.

CLI contract:
    python3 embed_html.py <input_path> <output_c_path> <symbol_name>

    input_path   — path to the source file (read as binary)
    output_c_path — path for the generated .c file (parent dir must exist)
    symbol_name  — C identifier used for the byte-array and length constant

The generated file declares:
    const uint8_t  <symbol_name>[];
    const size_t   <symbol_name>_len;

Bytes are gzip-compressed (level 9, mtime=0 for reproducible output).
Encoding/mime declarations are the consumer's responsibility.

Prints a one-line status to stdout on success.
Exits nonzero with a message on read/write errors.

Also usable as a PlatformIO pre-build script via SCons Import("env") — the
try/except at module level handles both contexts.
"""
import gzip
import io
import sys

# Support both standalone execution and PlatformIO pre-build script usage.
try:
    Import("env")  # noqa: F821 — SCons global; present only inside PlatformIO
except NameError:
    pass


def embed(input_path, output_c_path, symbol_name):
    """Read input_path, gzip-compress it, write a C source file to output_c_path."""
    try:
        with open(input_path, "rb") as f:
            raw = f.read()
    except OSError as e:
        print(f"embed_html: error reading {input_path}: {e}", file=sys.stderr)
        sys.exit(1)

    bio = io.BytesIO()
    with gzip.GzipFile(fileobj=bio, mode="wb", mtime=0) as gz:
        gz.write(raw)
    data = bio.getvalue()

    import os
    basename = os.path.basename(input_path)

    lines = [
        "// Auto-generated by breadboard/scripts/embed_html.py — do not edit.",
        f"// Source: {basename}",
        "#include <stddef.h>",
        "#include <stdint.h>",
        f"const uint8_t {symbol_name}[] = {{",
    ]

    # 16 bytes per line
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    lines += [
        "};",
        f"const size_t {symbol_name}_len = sizeof({symbol_name});",
    ]

    try:
        with open(output_c_path, "w") as f:
            f.write("\n".join(lines) + "\n")
    except OSError as e:
        print(f"embed_html: error writing {output_c_path}: {e}", file=sys.stderr)
        sys.exit(1)

    print(
        f"embed_html: {basename} -> {output_c_path} "
        f"({len(raw)} bytes -> {len(data)} bytes compressed)"
    )


def main():
    if len(sys.argv) != 4:
        print(
            "usage: embed_html.py <input_path> <output_c_path> <symbol_name>",
            file=sys.stderr,
        )
        sys.exit(1)

    _, input_path, output_c_path, symbol_name = sys.argv
    embed(input_path, output_c_path, symbol_name)


if __name__ == "__main__":
    main()
