#!/usr/bin/env python3
"""Generate components/README.md — an index of all components/<name>/ dirs.

GENERATED FILE. Do not hand-edit components/README.md; re-run this script
instead: `python3 scripts/gen_components_readme.py`.

Run with --check to verify the committed components/README.md matches what
this script would generate (drift check for CI / `make check`).
"""

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
COMPONENTS_DIR = REPO_ROOT / "components"
OUTPUT_FILE = COMPONENTS_DIR / "README.md"

HEADER = """# Components

This directory holds breadboard's reusable components. Each `components/<name>/`
directory is the **portable** surface for one component: public headers, Kconfig,
and CMakeLists. Platform-specific implementations live under
`platform/{host,espidf,arduino}/<name>/` (sibling to `components/`, not nested
inside it) — the portable component declares the API, the platform tree provides
the backend(s).

**This file is GENERATED by `scripts/gen_components_readme.py` — do not hand-edit
it.** Regenerate via `python3 scripts/gen_components_readme.py` after adding,
removing, or documenting a component.

See the top-level [README](../README.md) and [CLAUDE.md](../CLAUDE.md) for
project-wide conventions, build instructions, and architecture notes.

## Index
"""


def extract_purpose(readme_path: Path) -> str:
    """Pull a one-line Purpose out of a component README.md.

    Skips blank lines, skips a leading `#`-title line, then returns the first
    non-blank prose line that follows (trimmed). Returns "—" if the README
    has no such line.
    """
    lines = readme_path.read_text(encoding="utf-8").splitlines()
    idx = 0
    n = len(lines)

    # skip leading blank lines
    while idx < n and not lines[idx].strip():
        idx += 1

    # skip a leading title line (e.g. "# bb_x")
    if idx < n and lines[idx].lstrip().startswith("#"):
        idx += 1

    # skip blank lines between title and prose
    while idx < n and not lines[idx].strip():
        idx += 1

    if idx < n and lines[idx].strip():
        return lines[idx].strip()

    return "—"  # em dash


def collect_components():
    """Return [(name, purpose), ...] for every component dir, alphabetized."""
    entries = []
    for child in COMPONENTS_DIR.iterdir():
        if not child.is_dir():
            continue
        if child.name == "platform":
            continue
        readme = child / "README.md"
        if readme.is_file():
            purpose = extract_purpose(readme)
        else:
            purpose = "—"
        entries.append((child.name, purpose))
    entries.sort(key=lambda e: e[0])
    return entries


def build_content() -> str:
    """Build the full expected components/README.md content (header + table)."""
    entries = collect_components()

    lines = [HEADER.rstrip("\n"), ""]
    lines.append("| Component | Purpose |")
    lines.append("|-----------|---------|")
    for name, purpose in entries:
        lines.append(f"| [{name}](./{name}/) | {purpose} |")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify components/README.md matches generated content; exit non-zero on drift",
    )
    args = parser.parse_args()

    expected = build_content()

    if args.check:
        if not OUTPUT_FILE.is_file():
            print(f"error: {OUTPUT_FILE} does not exist.", file=sys.stderr)
            print(
                "Run `python3 scripts/gen_components_readme.py` to generate it.",
                file=sys.stderr,
            )
            return 1
        actual = OUTPUT_FILE.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"error: {OUTPUT_FILE} is stale (out of date with components/ on disk).",
                file=sys.stderr,
            )
            print(
                "Run `python3 scripts/gen_components_readme.py` to regenerate it, "
                "then commit the result.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_FILE.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
