#!/usr/bin/env python3
"""Generate components/README.md — an index of all components/<name>/ dirs.

GENERATED FILE. Do not hand-edit components/README.md; re-run this script
instead: `python3 scripts/gen_components_readme.py`.

Run with --check to verify the committed components/README.md matches what
this script would generate (drift check for CI / `make check`).
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "bbtool"))
from header_annot import extract_brief, primary_header  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
COMPONENTS_DIR = REPO_ROOT / "components"
OUTPUT_FILE = COMPONENTS_DIR / "README.md"

HEADER = """# Components

This directory holds breadboard's reusable components. Each `components/<name>/`
directory is the **portable** surface for one component: public headers, Kconfig,
and CMakeLists. Platform-specific implementations live under
`platform/{host,espidf,arduino}/<name>/` (sibling to `components/`, not nested
inside it) — the portable component declares the API, the platform tree provides
the backend(s).

See the top-level [README](../README.md) and [CLAUDE.md](../CLAUDE.md) for
project-wide conventions, build instructions, and architecture notes.

## Index
"""

FOOTER = """
_Generated by `scripts/gen_components_readme.py` — see [doc conventions](../wiki/Component-Docs)._
"""

_COMMENT_LINE_RE = re.compile(r'^\s*<!--.*-->\s*$')


def _first_prose_line(readme_path: Path) -> str:
    """README fallback: skip blank lines, a leading `#`-title line, and any
    bare `<!-- ... -->` marker lines, then return the first non-blank prose
    line that follows (trimmed). Returns "—" if the README has no such
    line."""
    lines = readme_path.read_text(encoding="utf-8").splitlines()
    idx = 0
    n = len(lines)

    def _skip_noise(i: int) -> int:
        while i < n and (not lines[i].strip() or _COMMENT_LINE_RE.match(lines[i])):
            i += 1
        return i

    idx = _skip_noise(idx)
    if idx < n and lines[idx].lstrip().startswith("#"):
        idx += 1
    idx = _skip_noise(idx)

    if idx < n and lines[idx].strip():
        return lines[idx].strip()

    return "—"  # em dash


def extract_purpose(readme_path: Path, name: str) -> str:
    """Pull a one-line Purpose for component `name`: sourced from its
    primary public header's `@brief` when present, else falls back to the
    README's first prose line (marker-skipping)."""
    header = primary_header(REPO_ROOT, name)
    brief = extract_brief(header)
    if brief:
        return brief
    return _first_prose_line(readme_path)


def collect_components():
    """Return [(name, purpose), ...] for every component dir, alphabetized."""
    entries = []
    for child in COMPONENTS_DIR.iterdir():
        if not child.is_dir():
            continue
        if child.name == "platform":
            continue
        readme = child / "README.md"
        if readme.is_file():
            purpose = extract_purpose(readme, child.name)
        else:
            purpose = "—"
        entries.append((child.name, purpose))
    entries.sort(key=lambda e: e[0])
    return entries


def build_content() -> str:
    """Build the full expected components/README.md content (header + table)."""
    entries = collect_components()

    lines = [HEADER.rstrip("\n"), ""]
    lines.append("| Component | Purpose |")
    lines.append("|-----------|---------|")
    for name, purpose in entries:
        lines.append(f"| [{name}](./{name}/) | {purpose} |")
    lines.append("")
    lines.append("---")
    lines.append(FOOTER.strip("\n"))

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify components/README.md matches generated content; exit non-zero on drift",
    )
    args = parser.parse_args()

    expected = build_content()

    if args.check:
        if not OUTPUT_FILE.is_file():
            print(f"error: {OUTPUT_FILE} does not exist.", file=sys.stderr)
            print(
                "Run `python3 scripts/gen_components_readme.py` to generate it.",
                file=sys.stderr,
            )
            return 1
        actual = OUTPUT_FILE.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"error: {OUTPUT_FILE} is stale (out of date with components/ on disk).",
                file=sys.stderr,
            )
            print(
                "Run `python3 scripts/gen_components_readme.py` to regenerate it, "
                "then commit the result.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_FILE.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
