#!/usr/bin/env python3
"""Generate components/README.md and every components/<group>/README.md's
generated index region — a two-level index of every discovered component,
grouped by `components/<group>/<name>/` directory (B1-1084 hierarchical
layout, PR3 of the depth-agnostic-layout lane).

GENERATED FILE (components/README.md). Do not hand-edit it; re-run this
script instead: `python3 scripts/gen_components_readme.py`. A group README
(components/<group>/README.md) is PARTIALLY generated: everything outside
its `<!-- BEGIN bbtool:group-index --> ... <!-- END bbtool:group-index -->`
marker region is hand-authored prose and is never touched.

Run with --check to verify every generated file (the top-level index, plus
every group's marker region) matches what this script would generate (drift
check for CI / `make check`, via `docs-index-check`).

Component discovery is routed through the discovery SSOT
(`scripts/bbtool/discovery.py`'s leaf rule: a component is the innermost
directory under `components/` that directly contains a `CMakeLists.txt`),
not a depth-1 `iterdir()` — so a component nested under
`components/<group>/<name>/` is found exactly like a flat
`components/<name>/` one. On today's flat tree (no group directories exist
yet) this degenerates byte-identically to the pre-hierarchy single-level
index.
"""

import argparse
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "bbtool"))
from header_annot import extract_brief, primary_header  # noqa: E402
from discovery import build_index  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
COMPONENTS_DIR = REPO_ROOT / "components"
OUTPUT_FILE = COMPONENTS_DIR / "README.md"

HEADER = """# Components

This directory holds breadboard's reusable components. Each `components/<name>/`
directory is the **portable** surface for one component: public headers, Kconfig,
and CMakeLists. Platform-specific implementations live under
`platform/{host,espidf,arduino}/<name>/` (sibling to `components/`, not nested
inside it) — the portable component declares the API, the platform tree provides
the backend(s).

See the top-level [README](../README.md) and [CLAUDE.md](../CLAUDE.md) for
project-wide conventions, build instructions, and architecture notes.

## Index
"""

FOOTER = """
_Generated by `scripts/gen_components_readme.py` — see [doc conventions](../wiki/Component-Docs)._
"""

# Marker delimiting the GENERATED index region inside a group's own
# components/<group>/README.md — everything above it is hand-authored prose
# (stamped as a placeholder by `bbtool docs scaffold --group`, then edited by
# a human), mirroring the HEADER/FOOTER split above but scoped to just the
# index table rather than the whole file (a group README needs room for
# hand-authored description text this top-level page's HEADER doesn't).
GROUP_INDEX_BEGIN = "<!-- BEGIN bbtool:group-index -->"
GROUP_INDEX_END = "<!-- END bbtool:group-index -->"
_GROUP_INDEX_RE = re.compile(
    re.escape(GROUP_INDEX_BEGIN) + r"\r?\n.*?\r?\n" + re.escape(GROUP_INDEX_END),
    re.DOTALL,
)

_COMMENT_LINE_RE = re.compile(r'^\s*<!--.*-->\s*$')


def _first_prose_line(readme_path: Path) -> str:
    """README fallback: skip blank lines, a leading `#`-title line, and any
    bare `<!-- ... -->` marker lines, then return the first non-blank prose
    line that follows (trimmed). Returns "—" if the README has no such
    line."""
    lines = readme_path.read_text(encoding="utf-8").splitlines()
    idx = 0
    n = len(lines)

    def _skip_noise(i: int) -> int:
        while i < n and (not lines[i].strip() or _COMMENT_LINE_RE.match(lines[i])):
            i += 1
        return i

    idx = _skip_noise(idx)
    if idx < n and lines[idx].lstrip().startswith("#"):
        idx += 1
    idx = _skip_noise(idx)

    if idx < n and lines[idx].strip():
        return lines[idx].strip()

    return "—"  # em dash


class ComponentIndexError(Exception):
    """Raised when a `components/<name>/` directory found by this script's
    top-level walk isn't actually a discovered component —
    `header_annot.primary_header` returns `None` because no `CMakeLists.txt`
    was found anywhere under `components/<name>/` (a bare/orphan directory —
    not itself a leaf, and with no leaf components nested under it either;
    see discovery.py's leaf rule). Fail loud rather than either (a) crash on
    `extract_brief(None)`, or (b) silently skip/placeholder the entry — a
    skip would produce a WRONG index (a real on-disk directory quietly
    missing from components/README.md), which is exactly the drift this
    script exists to catch."""


class GroupReadmeError(Exception):
    """Raised when a components/<group>/ directory contains one or more
    discovered leaf components but has no README.md of its own, or its
    README.md has no `bbtool:group-index` marker region — a group must be
    documented (see `bbtool docs scaffold --group <name>`) before it can
    appear in the generated index; never silently render an em-dash
    description or skip the group's own index."""


def extract_purpose(readme_path: Path, name: str) -> str:
    """Pull a one-line Purpose for component `name`: sourced from its
    primary public header's `@brief` when present, else falls back to the
    README's first prose line (marker-skipping). Raises ComponentIndexError
    if `name` isn't a real discovered component (see that class's
    docstring)."""
    header = primary_header(REPO_ROOT, name)
    if header is None:
        raise ComponentIndexError(
            f"components/{name}/ has a README.md but is not a discovered"
            f" component (no CMakeLists.txt found under components/{name}/)"
            " — cannot source its Purpose"
        )
    brief = extract_brief(header)
    if brief:
        return brief
    return _first_prose_line(readme_path)


def _leaf_components_under(index, group_dir: Path):
    """Return sorted [(name, comp_dir), ...] for every discovered leaf
    component (per the discovery SSOT) whose comp_dir is nested anywhere
    under `group_dir`."""
    out = []
    for name in index.names():
        comp_dir = index.component_dir(name)
        if comp_dir is None:
            continue
        try:
            comp_dir.relative_to(group_dir)
        except ValueError:
            continue
        out.append((name, comp_dir))
    out.sort(key=lambda t: t[0])
    return out


def discover_tree():
    """Classify every top-level components/<child>/ directory as either an
    ungrouped component (today's flat convention — including the
    pre-hierarchy bare/orphan-directory edge case, preserved unchanged) or a
    GROUP (an intermediate directory with no CMakeLists.txt of its own, but
    that has one or more discovered leaf components nested under it).

    Returns (ungrouped, groups):
      ungrouped = [(name, purpose), ...], sorted by name.
      groups    = [(group_name, description, group_dir, members), ...],
                  sorted by group_name, where members is
                  [(name, comp_dir, purpose), ...] sorted by name.

    Routed through the discovery SSOT (`discovery.build_index`) for
    component/group classification rather than a fixed depth-1 assumption —
    the top-level `components/` listing itself still needs a plain
    directory walk (not `index.names()` alone) so a bare/orphan directory
    with no discovered component anywhere under it still surfaces the
    ComponentIndexError a flat-layout drift check depends on."""
    # `discovery.build_index` canonicalizes its root via `os.path.realpath`
    # before scanning, so every `ComponentEntry.component_dir` it returns is
    # realpath-rooted. Walk the SAME canonicalized `components/` dir here
    # (rather than `COMPONENTS_DIR` verbatim) so `leaf_dir == child` and
    # `comp_dir.relative_to(child)` below compare like-rooted paths — a
    # symlinked repo/tmp root (e.g. macOS's /var -> /private/var) would
    # otherwise make every comparison spuriously fail.
    comp_root = Path(os.path.realpath(str(COMPONENTS_DIR)))
    if not comp_root.is_dir():
        return [], []

    index = build_index([str(REPO_ROOT)])
    ungrouped = []
    groups = []

    for child in sorted(comp_root.iterdir(), key=lambda p: p.name):
        if not child.is_dir():
            continue

        leaf_dir = index.component_dir(child.name)
        if leaf_dir is not None and leaf_dir == child:
            # A top-level leaf component (today's flat convention).
            readme = child / "README.md"
            purpose = extract_purpose(readme, child.name) if readme.is_file() else "—"
            ungrouped.append((child.name, purpose))
            continue

        members = _leaf_components_under(index, child)
        if members:
            group_readme = child / "README.md"
            if not group_readme.is_file():
                raise GroupReadmeError(
                    f"components/{child.name}/ contains {len(members)} discovered"
                    f" component(s) but has no README.md — add a hand-authored"
                    f" components/{child.name}/README.md (see"
                    " `bbtool docs scaffold --group`)"
                )
            desc = _first_prose_line(group_readme)
            group_members = []
            for name, comp_dir in members:
                readme = comp_dir / "README.md"
                purpose = extract_purpose(readme, name) if readme.is_file() else "—"
                group_members.append((name, comp_dir, purpose))
            groups.append((child.name, desc, child, group_members))
            continue

        # Orphan / non-component directory — preserve pre-hierarchy
        # behavior exactly: a README triggers extract_purpose (which raises
        # ComponentIndexError since `child.name` isn't discovered); no
        # README is just an em-dash entry.
        readme = child / "README.md"
        purpose = extract_purpose(readme, child.name) if readme.is_file() else "—"
        ungrouped.append((child.name, purpose))

    ungrouped.sort(key=lambda e: e[0])
    groups.sort(key=lambda e: e[0])
    return ungrouped, groups


def collect_components():
    """Return [(name, purpose), ...] for every UNGROUPED component dir,
    alphabetized — the pre-hierarchy contract, preserved for existing
    callers/tests. Group summary rows are a `build_content()`-only concern
    (see `discover_tree`)."""
    ungrouped, _groups = discover_tree()
    return ungrouped


def build_content() -> str:
    """Build the full expected components/README.md content: one row per
    ungrouped component (unchanged pre-hierarchy shape) plus one row per
    GROUP (name/desc sourced from that group's own README), merged and
    sorted alphabetically together. Byte-identical to the pre-hierarchy
    output when no group directories exist (today's tree)."""
    ungrouped, groups = discover_tree()

    entries = []
    for name, purpose in ungrouped:
        entries.append((name, f"| [{name}](./{name}/) | {purpose} |"))
    for group_name, desc, _group_dir, _members in groups:
        entries.append((group_name, f"| [{group_name}/](./{group_name}/) | {desc} |"))
    entries.sort(key=lambda e: e[0])

    lines = [HEADER.rstrip("\n"), ""]
    lines.append("| Component | Purpose |")
    lines.append("|-----------|---------|")
    for _, row in entries:
        lines.append(row)
    lines.append("")
    lines.append("---")
    lines.append(FOOTER.strip("\n"))

    return "\n".join(lines) + "\n"


def _group_index_table(group_dir: Path, members) -> str:
    lines = ["| Component | Purpose |", "|-----------|---------|"]
    for name, comp_dir, purpose in members:
        rel = comp_dir.relative_to(group_dir).as_posix()
        lines.append(f"| [{name}](./{rel}/) | {purpose} |")
    return "\n".join(lines)


def build_group_readme(group_name: str, group_dir: Path, members) -> str:
    """Return the full expected content of components/<group_name>/README.md:
    the existing file's content, with its `bbtool:group-index` marker
    region's body replaced by a freshly-rendered index table over `members`.
    Everything outside the marker region is left byte-for-byte untouched.
    Raises GroupReadmeError if the README is missing or has no
    `bbtool:group-index` marker region."""
    readme_path = group_dir / "README.md"
    if not readme_path.is_file():
        raise GroupReadmeError(
            f"components/{group_name}/ contains {len(members)} discovered"
            f" component(s) but has no README.md — add a hand-authored"
            f" components/{group_name}/README.md (see"
            " `bbtool docs scaffold --group`)"
        )
    content = readme_path.read_text(encoding="utf-8")
    if not _GROUP_INDEX_RE.search(content):
        raise GroupReadmeError(
            f"components/{group_name}/README.md has no bbtool:group-index"
            " marker region — add one (see `bbtool docs scaffold --group`)"
        )
    table = _group_index_table(group_dir, members)
    block = f"{GROUP_INDEX_BEGIN}\n{table}\n{GROUP_INDEX_END}"
    return _GROUP_INDEX_RE.sub(lambda _m: block, content, count=1)


def build_group_contents():
    """Return [(readme_path, expected_content), ...] for every discovered
    group, sorted by group name."""
    _ungrouped, groups = discover_tree()
    out = []
    for group_name, _desc, group_dir, members in groups:
        content = build_group_readme(group_name, group_dir, members)
        out.append((group_dir / "README.md", content))
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify components/README.md and every group README's generated"
             " index region match generated content; exit non-zero on drift",
    )
    args = parser.parse_args()

    try:
        expected_top = build_content()
        expected_groups = build_group_contents()
    except (ComponentIndexError, GroupReadmeError) as exc:
        print(f"gen_components_readme: error: {exc}", file=sys.stderr)
        return 1

    targets = [(OUTPUT_FILE, expected_top)] + expected_groups

    if args.check:
        failed = False
        for path, expected in targets:
            if not path.is_file():
                print(f"error: {path} does not exist.", file=sys.stderr)
                print(
                    "Run `python3 scripts/gen_components_readme.py` to generate it.",
                    file=sys.stderr,
                )
                failed = True
                continue
            actual = path.read_text(encoding="utf-8")
            if actual != expected:
                print(
                    f"error: {path} is stale (out of date with components/ on disk).",
                    file=sys.stderr,
                )
                print(
                    "Run `python3 scripts/gen_components_readme.py` to regenerate it, "
                    "then commit the result.",
                    file=sys.stderr,
                )
                failed = True
        return 1 if failed else 0

    for path, expected in targets:
        path.write_text(expected, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
