"""gen_site.py — embed an entire built-SPA dist/ directory into firmware.

CLI contract:
    python3 gen_site.py <dist_dir> <out_dir> <table_sym> [--url-prefix /]

    dist_dir    — path to the built SPA output directory (e.g. dist/)
    out_dir     — directory where generated .c files are written (must exist)
    table_sym   — C identifier prefix for the asset table and blobs
                  (e.g. "demo_site" → demo_site[], demo_site__assets_index_js[])
    --url-prefix — URL root to prepend to asset paths (default "/")

For each regular file found under dist_dir:
  - relpath   = POSIX path relative to dist_dir, e.g. "assets/index.js"
  - url       = "/" for dist-root index.html; otherwise "/<relpath>" (or
                url_prefix + relpath when url_prefix != "/")
  - symbol    = <table_sym>__ + relpath sanitized to a C identifier
                (non-alnum chars → "_"), e.g. demo_site__assets_index_js
  - mime      derived from file extension (see MIME_MAP)
  - encoding  = "gzip" (all blobs are gzip-compressed via embed_html)

Writes:
  <out_dir>/<symbol>.c          — one gzipped blob per file (via embed_html)
  <out_dir>/<table_sym>_table.c — bb_http_asset_t[] table + lazy accessor

Accessor shape (printed in table .c header comment and chosen for c99 + ESP-IDF
portability):

    bb_http_asset_t <table_sym>[];           // mutable table (len filled at runtime)
    const bb_http_asset_t *<table_sym>_get(size_t *n);

The table is declared as a non-const mutable array so each entry's .data and
.len can be filled from the extern blob symbols on first call without violating
C99 const rules.  <table_sym>_get() is idempotent — subsequent calls just
return the already-initialised table.  The pattern mirrors bb_prov_default_form.

Prints the absolute path of every generated .c file to stdout (one per line,
sorted) so that CMake execute_process(OUTPUT_VARIABLE …) can capture the list.
"""

import argparse
import os
import re
import sys

# Importable gzip+emit helper from embed_html.
# We need the directory containing this script on sys.path so the import works
# even when invoked from a different working directory (e.g. CMake's cwd).
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

import embed_html  # noqa: E402 — must come after sys.path fixup

# ---------------------------------------------------------------------------
# MIME map — extension (lowercase, with dot) → MIME type
# ---------------------------------------------------------------------------
MIME_MAP = {
    ".html": "text/html",
    ".htm":  "text/html",
    ".js":   "application/javascript",
    ".mjs":  "application/javascript",
    ".css":  "text/css",
    ".svg":  "image/svg+xml",
    ".json": "application/json",
    ".ico":  "image/x-icon",
    ".png":  "image/png",
    ".woff2": "font/woff2",
    ".txt":  "text/plain",
}
_DEFAULT_MIME = "application/octet-stream"


def _mime(path):
    _, ext = os.path.splitext(path)
    return MIME_MAP.get(ext.lower(), _DEFAULT_MIME)


def _sanitize(name):
    """Replace every non-alphanumeric character with '_'."""
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def _symbol(table_sym, relpath_posix):
    return table_sym + "__" + _sanitize(relpath_posix)


def _url(relpath_posix, url_prefix):
    # dist-root index.html → "/"
    if relpath_posix == "index.html":
        return "/"
    if url_prefix == "/":
        return "/" + relpath_posix
    # strip trailing slash from prefix then join
    return url_prefix.rstrip("/") + "/" + relpath_posix


def _collect_files(dist_dir):
    """Return sorted list of (relpath_posix, abs_path) for every regular file."""
    entries = []
    for root, dirs, files in os.walk(dist_dir):
        dirs.sort()   # deterministic traversal
        for fname in sorted(files):
            abs_path = os.path.join(root, fname)
            rel = os.path.relpath(abs_path, dist_dir)
            # normalise to posix separators
            rel_posix = rel.replace(os.sep, "/")
            entries.append((rel_posix, abs_path))
    return entries


def _write_table(out_dir, table_sym, entries, url_prefix):
    """Emit <table_sym>_table.c with extern decls, mutable table, and accessor."""
    table_c = os.path.join(out_dir, table_sym + "_table.c")
    n = len(entries)

    lines = [
        "// Auto-generated by breadboard/scripts/gen_site.py — do not edit.",
        "//",
        "// Accessor contract (c99-portable, ESP-IDF compatible):",
        "//",
        "//   bb_http_asset_t <table_sym>[];",
        "//   const bb_http_asset_t *<table_sym>_get(size_t *n);",
        "//",
        "// The table is non-const so .data and .len can be filled lazily from",
        "// the extern blob symbols on first call.  <table_sym>_get() is",
        "// idempotent — subsequent calls return the same pointer.",
        "",
        '#include "bb_http.h"',
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]

    # extern declarations for every blob
    for rel_posix, _ in entries:
        sym = _symbol(table_sym, rel_posix)
        lines.append(f"extern const uint8_t {sym}[];")
        lines.append(f"extern const size_t  {sym}_len;")

    lines += [
        "",
        f"bb_http_asset_t {table_sym}[{n}];",
        f"const size_t {table_sym}_count = {n};",
        "",
        f"const bb_http_asset_t *{table_sym}_get(size_t *n) {{",
        "    static int s_init = 0;",
        "    if (!s_init) {",
    ]

    for i, (rel_posix, _) in enumerate(entries):
        sym = _symbol(table_sym, rel_posix)
        url = _url(rel_posix, url_prefix)
        mime = _mime(rel_posix)
        lines += [
            f'        {table_sym}[{i}].path     = "{url}";',
            f'        {table_sym}[{i}].mime     = "{mime}";',
            f'        {table_sym}[{i}].encoding = "gzip";',
            f"        {table_sym}[{i}].data     = {sym};",
            f"        {table_sym}[{i}].len      = {sym}_len;",
        ]

    lines += [
        "        s_init = 1;",
        "    }",
        f"    if (n) {{ *n = {table_sym}_count; }}",
        f"    return {table_sym};",
        "}",
    ]

    try:
        with open(table_c, "w") as f:
            f.write("\n".join(lines) + "\n")
    except OSError as e:
        print(f"gen_site: error writing {table_c}: {e}", file=sys.stderr)
        sys.exit(1)

    return table_c


def generate(dist_dir, out_dir, table_sym, url_prefix="/"):
    """Main logic. Returns sorted list of generated absolute .c paths."""
    dist_dir = os.path.abspath(dist_dir)
    out_dir  = os.path.abspath(out_dir)

    if not os.path.isdir(dist_dir):
        print(f"gen_site: dist_dir not found: {dist_dir}", file=sys.stderr)
        sys.exit(1)

    os.makedirs(out_dir, exist_ok=True)

    entries = _collect_files(dist_dir)
    if not entries:
        print(f"gen_site: no files found under {dist_dir}", file=sys.stderr)
        sys.exit(1)

    generated = []

    # Emit one blob .c per file
    for rel_posix, abs_path in entries:
        sym = _symbol(table_sym, rel_posix)
        out_c = os.path.join(out_dir, sym + ".c")
        embed_html.embed_file(abs_path, out_c, sym)
        generated.append(os.path.abspath(out_c))

    # Emit table .c
    table_c = _write_table(out_dir, table_sym, entries, url_prefix)
    generated.append(os.path.abspath(table_c))

    return sorted(generated)


def main():
    parser = argparse.ArgumentParser(
        description="Embed a built-SPA dist/ directory into firmware as gzipped C blobs."
    )
    parser.add_argument("dist_dir",  help="Path to the dist directory")
    parser.add_argument("out_dir",   help="Directory for generated .c files")
    parser.add_argument("table_sym", help="C identifier prefix for the asset table")
    parser.add_argument("--url-prefix", default="/",
                        help="URL root prepended to asset paths (default '/')")
    args = parser.parse_args()

    generated = generate(args.dist_dir, args.out_dir, args.table_sym,
                         url_prefix=args.url_prefix)

    # Print absolute paths to stdout — one per line — for CMake to capture.
    for path in generated:
        print(path)


if __name__ == "__main__":
    main()
